"""Crossword puzzle generator with dictionary validation.

Generates valid 5x5 mini crosswords with 1-5 black squares.
All words are validated against the dictionary database.
"""

import logging
import random
from typing import Optional
from sqlalchemy.orm import Session

from app.models.cache_meta import DictionaryWord

logger = logging.getLogger(__name__)

# Black square marker
BLACK = "#"

# Pre-defined grid patterns with black squares - easier to fill patterns
PATTERNS = [
    # Pattern 1: Simple - no black squares (10 words: 5 across + 5 down, all 5 letters)
    [
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
    ],
    # Pattern 2: Two corners - creates 4-letter words at edges
    [
        [BLACK, ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", BLACK],
    ],
    # Pattern 3: Other two corners
    [
        [".", ".", ".", ".", BLACK],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [BLACK, ".", ".", ".", "."],
    ],
    # Pattern 4: Four corners - creates 3-letter edge words
    [
        [BLACK, ".", ".", ".", BLACK],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [BLACK, ".", ".", ".", BLACK],
    ],
    # Pattern 5: Center black - creates 2+2 letter splits (may need adjustment)
    [
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", BLACK, ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
    ],
    # Pattern 6: Left and right center
    [
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [BLACK, ".", ".", ".", BLACK],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
    ],
    # Pattern 7: Top and bottom center
    [
        [".", ".", BLACK, ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", BLACK, ".", "."],
    ],
]

# Simple clue templates based on common word patterns
CLUE_TEMPLATES = {
    # Common 3-letter words
    "THE": "Definite article",
    "AND": "Plus",
    "FOR": "In favor of",
    "ARE": "Exist (plural)",
    "BUT": "However",
    "NOT": "Negative",
    "YOU": "Second person pronoun",
    "ALL": "Everything",
    "CAN": "Able to",
    "HAD": "Possessed",
    "HER": "Belonging to her",
    "WAS": "Past tense of be",
    "ONE": "Single",
    "OUR": "Belonging to us",
    "OUT": "Not in",
    "DAY": "24 hours",
    "GET": "Obtain",
    "HAS": "Possesses",
    "HIM": "That man",
    "HIS": "Belonging to him",
    "HOW": "In what way",
    "MAN": "Adult male",
    "NEW": "Not old",
    "NOW": "At this moment",
    "OLD": "Not new",
    "SEE": "View",
    "WAY": "Path",
    "WHO": "Which person",
    "BOY": "Young male",
    "DID": "Past tense of do",
    "ITS": "Belonging to it",
    "LET": "Allow",
    "PUT": "Place",
    "SAY": "Speak",
    "SHE": "That woman",
    "TOO": "Also",
    "USE": "Utilize",
    "CAT": "Feline pet",
    "DOG": "Canine pet",
    "RUN": "Move fast",
    "SUN": "Star",
    "RED": "Color of blood",
    "BIG": "Large",
    "END": "Finish",
    "SET": "Group",
    "TOP": "Highest point",
    "ACE": "Tennis serve",
    "ADD": "Sum up",
    "AGE": "Years old",
    "AGO": "In the past",
    "AID": "Help",
    "AIM": "Target",
    "AIR": "Atmosphere",
    "APE": "Primate",
    "ARC": "Curve",
    "ARK": "Noah's boat",
    "ARM": "Limb",
    "ART": "Creative work",
    "ATE": "Consumed",
    "AWE": "Wonder",
    "AXE": "Chopping tool",
    "BAD": "Not good",
    "BAG": "Sack",
    "BAN": "Prohibit",
    "BAR": "Pub",
    "BAT": "Flying mammal",
    "BED": "Sleeping furniture",
    "BET": "Wager",
    "BIT": "Small piece",
    "BOW": "Bend forward",
    "BOX": "Container",
    "BUS": "Public vehicle",
    "BUY": "Purchase",
    "CAB": "Taxi",
    "CAP": "Hat",
    "CAR": "Automobile",
    "COP": "Police officer",
    "COW": "Farm animal",
    "CRY": "Weep",
    "CUP": "Drinking vessel",
    "CUT": "Slice",
    "DAM": "Water barrier",
    "DEN": "Animal home",
    "DEW": "Morning moisture",
    "DIE": "Perish",
    "DIG": "Excavate",
    "DIM": "Not bright",
    "DIP": "Submerge briefly",
    "DOT": "Small spot",
    "DRY": "Not wet",
    "DUE": "Owed",
    "DUG": "Excavated",
    "EAR": "Hearing organ",
    "EAT": "Consume food",
    "EEL": "Snake-like fish",
    "EGG": "Oval food",
    "ELF": "Mythical being",
    "ELM": "Type of tree",
    "ERA": "Time period",
    "EVE": "Evening",
    "EYE": "Seeing organ",
    "FAN": "Cooling device",
    "FAR": "Distant",
    "FAT": "Not thin",
    "FED": "Gave food",
    "FEW": "Not many",
    "FIG": "Fruit",
    "FIN": "Fish part",
    "FIT": "In shape",
    "FLY": "Soar",
    "FOG": "Mist",
    "FOX": "Cunning animal",
    "FUN": "Enjoyment",
    "FUR": "Animal coat",
    "GAP": "Opening",
    "GAS": "Fuel",
    "GEM": "Jewel",
    "GOT": "Obtained",
    "GUM": "Chewing candy",
    "GUN": "Firearm",
    "GUT": "Intestine",
    "GUY": "Man",
    "GYM": "Exercise place",
    "HAM": "Pork meat",
    "HAT": "Head covering",
    "HAY": "Dried grass",
    "HEN": "Female chicken",
    "HID": "Concealed",
    "HIP": "Body joint",
    "HIT": "Strike",
    "HOG": "Pig",
    "HOP": "Small jump",
    "HOT": "High temperature",
    "HUB": "Center",
    "HUG": "Embrace",
    "HUT": "Small shelter",
    "ICE": "Frozen water",
    "ICY": "Very cold",
    "ILL": "Sick",
    "INK": "Pen fluid",
    "INN": "Small hotel",
    "IRE": "Anger",
    "IVY": "Climbing plant",
    "JAM": "Fruit spread",
    "JAR": "Glass container",
    "JAW": "Mouth bone",
    "JET": "Fast plane",
    "JOB": "Work",
    "JOG": "Light run",
    "JOY": "Happiness",
    "JUG": "Pitcher",
    "KEG": "Barrel",
    "KEY": "Lock opener",
    "KID": "Child",
    "KIT": "Set of items",
    "LAB": "Laboratory",
    "LAD": "Young man",
    "LAP": "Circuit",
    "LAW": "Legal rule",
    "LAY": "Put down",
    "LEG": "Limb",
    "LID": "Cover",
    "LIE": "Falsehood",
    "LIP": "Mouth edge",
    "LOG": "Wood piece",
    "LOT": "Many",
    "LOW": "Not high",
    "MAD": "Angry",
    "MAP": "Chart",
    "MAT": "Floor covering",
    "MEN": "Adult males",
    "MET": "Encountered",
    "MIX": "Combine",
    "MOB": "Crowd",
    "MOM": "Mother",
    "MOP": "Cleaning tool",
    "MUD": "Wet dirt",
    "MUG": "Cup",
    "NAP": "Short sleep",
    "NET": "Mesh",
    "NIT": "Louse egg",
    "NOD": "Head gesture",
    "NOR": "And not",
    "NUN": "Religious woman",
    "NUT": "Hard seed",
    "OAK": "Tree type",
    "OAR": "Rowing tool",
    "OAT": "Grain",
    "ODD": "Strange",
    "OIL": "Lubricant",
    "ORB": "Sphere",
    "ORE": "Metal rock",
    "OWE": "Be in debt",
    "OWL": "Night bird",
    "OWN": "Possess",
    "PAD": "Cushion",
    "PAN": "Cooking pot",
    "PAT": "Light touch",
    "PAW": "Animal foot",
    "PAY": "Compensate",
    "PEA": "Green vegetable",
    "PEN": "Writing tool",
    "PET": "Animal companion",
    "PIE": "Baked dessert",
    "PIG": "Farm animal",
    "PIN": "Sharp fastener",
    "PIT": "Hole",
    "POD": "Seed case",
    "POP": "Father",
    "POT": "Container",
    "PUB": "Bar",
    "PUN": "Word play",
    "PUP": "Young dog",
    "RAG": "Cloth",
    "RAM": "Male sheep",
    "RAN": "Moved fast",
    "RAP": "Knock",
    "RAT": "Rodent",
    "RAW": "Uncooked",
    "RAY": "Light beam",
    "RIB": "Bone",
    "RID": "Free from",
    "RIG": "Equipment",
    "RIM": "Edge",
    "RIP": "Tear",
    "ROB": "Steal",
    "ROD": "Stick",
    "ROT": "Decay",
    "ROW": "Line",
    "RUB": "Massage",
    "RUG": "Floor covering",
    "SAD": "Unhappy",
    "SAP": "Tree fluid",
    "SAT": "Was seated",
    "SAW": "Cutting tool",
    "SEA": "Ocean",
    "SIP": "Drink slowly",
    "SIT": "Be seated",
    "SIX": "Number",
    "SKI": "Snow sport",
    "SKY": "Above",
    "SOB": "Cry loudly",
    "SOD": "Grass",
    "SON": "Male child",
    "SPA": "Resort",
    "SPY": "Secret agent",
    "STY": "Pig pen",
    "SUB": "Submarine",
    "SUM": "Total",
    "TAB": "Bill",
    "TAG": "Label",
    "TAN": "Brown color",
    "TAP": "Light knock",
    "TAR": "Black substance",
    "TAX": "Government fee",
    "TEA": "Hot drink",
    "TEN": "Number",
    "TIE": "Necktie",
    "TIN": "Metal",
    "TIP": "Point",
    "TOE": "Foot digit",
    "TON": "Heavy weight",
    "TOW": "Pull",
    "TOY": "Plaything",
    "TUB": "Bath container",
    "TUG": "Pull hard",
    "TWO": "Number",
    "URN": "Vase",
    "VAN": "Vehicle",
    "VAT": "Large container",
    "VET": "Animal doctor",
    "VIA": "By way of",
    "WAR": "Armed conflict",
    "WAX": "Candle material",
    "WEB": "Spider's creation",
    "WED": "Marry",
    "WET": "Not dry",
    "WIG": "Hair piece",
    "WIN": "Victory",
    "WIT": "Humor",
    "WOE": "Sorrow",
    "WOK": "Asian pan",
    "WON": "Achieved victory",
    "ZAP": "Hit with energy",
    "ZEN": "Buddhist concept",
    "ZIP": "Fasten",
    "ZIT": "Pimple",
    "ZOO": "Animal park",
    # Common 4-letter words
    "ABLE": "Capable",
    "ALSO": "In addition",
    "AREA": "Region",
    "ARMY": "Military force",
    "AWAY": "Not here",
    "BABY": "Infant",
    "BACK": "Rear",
    "BALL": "Round toy",
    "BAND": "Musical group",
    "BANK": "Financial institution",
    "BASE": "Foundation",
    "BEAR": "Large mammal",
    "BEAT": "Rhythm",
    "BEEN": "Past participle of be",
    "BELL": "Ringing device",
    "BEST": "Most good",
    "BIRD": "Flying animal",
    "BLOW": "Wind gust",
    "BLUE": "Sky color",
    "BOAT": "Water vessel",
    "BODY": "Physical form",
    "BOOK": "Reading material",
    "BORN": "Brought into life",
    "BOSS": "Manager",
    "BOTH": "Two together",
    "BOWL": "Deep dish",
    "BURN": "Be on fire",
    "CALL": "Phone",
    "CALM": "Peaceful",
    "CAME": "Arrived",
    "CAMP": "Outdoor stay",
    "CARD": "Paper rectangle",
    "CARE": "Concern",
    "CASE": "Instance",
    "CASH": "Money",
    "CAST": "Throw",
    "CELL": "Small room",
    "CITY": "Urban area",
    "CLUB": "Organization",
    "COAT": "Jacket",
    "CODE": "System",
    "COLD": "Low temperature",
    "COME": "Arrive",
    "COOK": "Prepare food",
    "COOL": "Slightly cold",
    "COPY": "Duplicate",
    "CORE": "Center",
    "COST": "Price",
    "DARK": "Without light",
    "DATA": "Information",
    "DATE": "Calendar day",
    "DEAD": "Not alive",
    "DEAL": "Agreement",
    "DEAR": "Beloved",
    "DEEP": "Not shallow",
    "DESK": "Work table",
    "DOES": "Performs",
    "DONE": "Finished",
    "DOOR": "Entrance",
    "DOWN": "Lower",
    "DRAW": "Sketch",
    "DREW": "Sketched",
    "DROP": "Fall",
    "DRUG": "Medicine",
    "EACH": "Every one",
    "EAST": "Direction",
    "EASY": "Not hard",
    "EDGE": "Border",
    "ELSE": "Otherwise",
    "EVEN": "Level",
    "EVER": "At any time",
    "FACE": "Front of head",
    "FACT": "Truth",
    "FAIL": "Not succeed",
    "FAIR": "Just",
    "FALL": "Autumn",
    "FARM": "Agricultural land",
    "FAST": "Quick",
    "FEAR": "Fright",
    "FEED": "Give food",
    "FEEL": "Sense",
    "FEET": "Plural of foot",
    "FELL": "Dropped",
    "FILE": "Document",
    "FILL": "Make full",
    "FILM": "Movie",
    "FIND": "Discover",
    "FINE": "Good",
    "FIRE": "Flame",
    "FIRM": "Company",
    "FISH": "Aquatic animal",
    "FIVE": "Number",
    "FLAT": "Level",
    "FLEW": "Past tense of fly",
    "FLOW": "Stream",
    "FOOD": "Nourishment",
    "FOOT": "Body part",
    "FORM": "Shape",
    "FORT": "Military building",
    "FOUR": "Number",
    "FREE": "Without cost",
    "FROM": "Starting point",
    "FULL": "Filled",
    "FUND": "Money supply",
    "GAIN": "Acquire",
    "GAME": "Sport",
    "GAVE": "Past of give",
    "GIRL": "Young female",
    "GIVE": "Present",
    "GLAD": "Happy",
    "GOAL": "Objective",
    "GOES": "Moves",
    "GOLD": "Precious metal",
    "GONE": "Departed",
    "GOOD": "Positive",
    "GREW": "Increased",
    "GROW": "Increase",
    "HAIR": "Head covering",
    "HALF": "50 percent",
    "HALL": "Corridor",
    "HAND": "Body part",
    "HANG": "Suspend",
    "HARD": "Not soft",
    "HARM": "Damage",
    "HATE": "Strongly dislike",
    "HAVE": "Possess",
    "HEAD": "Top of body",
    "HEAR": "Listen",
    "HEAT": "Warmth",
    "HELD": "Grasped",
    "HELP": "Assist",
    "HERE": "This place",
    "HERO": "Brave person",
    "HIGH": "Tall",
    "HILL": "Small mountain",
    "HOLD": "Grasp",
    "HOLE": "Opening",
    "HOME": "Residence",
    "HOPE": "Wish",
    "HOST": "Party giver",
    "HOUR": "60 minutes",
    "HUGE": "Very large",
    "HUNG": "Suspended",
    "HUNT": "Search",
    "HURT": "Injure",
    "IDEA": "Thought",
    "INTO": "Inside",
    "IRON": "Metal",
    "ITEM": "Thing",
    "JACK": "Card face",
    "JAZZ": "Music genre",
    "JEAN": "Denim pants",
    "JOBS": "Work positions",
    "JOIN": "Connect",
    "JOKE": "Funny story",
    "JUMP": "Leap",
    "JUNE": "Month",
    "JURY": "Trial group",
    "JUST": "Fair",
    "KEEP": "Retain",
    "KEPT": "Retained",
    "KICK": "Foot strike",
    "KILL": "End life",
    "KIND": "Type",
    "KING": "Male monarch",
    "KNEE": "Leg joint",
    "KNEW": "Was aware",
    "KNOW": "Be aware",
    "LACK": "Be without",
    "LADY": "Woman",
    "LAID": "Put down",
    "LAKE": "Body of water",
    "LAND": "Earth",
    "LANE": "Narrow road",
    "LAST": "Final",
    "LATE": "Not on time",
    "LEAD": "Guide",
    "LEFT": "Opposite of right",
    "LESS": "Fewer",
    "LIFE": "Existence",
    "LIFT": "Raise",
    "LIKE": "Similar to",
    "LINE": "Row",
    "LINK": "Connection",
    "LIST": "Catalog",
    "LIVE": "Be alive",
    "LOAD": "Cargo",
    "LOAN": "Borrowed money",
    "LOCK": "Security device",
    "LOGO": "Brand symbol",
    "LONG": "Extended",
    "LOOK": "See",
    "LORD": "Nobleman",
    "LOSE": "Misplace",
    "LOSS": "Defeat",
    "LOST": "Misplaced",
    "LOTS": "Many",
    "LOVE": "Deep affection",
    "LUCK": "Fortune",
    "MADE": "Created",
    "MAIL": "Postal service",
    "MAIN": "Primary",
    "MAKE": "Create",
    "MALE": "Man",
    "MANY": "A lot",
    "MARK": "Sign",
    "MASS": "Large amount",
    "MEAL": "Food serving",
    "MEAN": "Intend",
    "MEET": "Encounter",
    "MENU": "Food list",
    "MILE": "Distance unit",
    "MILK": "Dairy drink",
    "MIND": "Brain",
    "MINE": "Belonging to me",
    "MISS": "Fail to hit",
    "MODE": "Method",
    "MOON": "Night light",
    "MORE": "Additional",
    "MOST": "Greatest amount",
    "MOVE": "Change position",
    "MUCH": "A lot",
    "MUST": "Have to",
    "NAME": "Title",
    "NEAR": "Close",
    "NECK": "Body part",
    "NEED": "Require",
    "NEWS": "Information",
    "NEXT": "Following",
    "NICE": "Pleasant",
    "NINE": "Number",
    "NONE": "Not any",
    "NOON": "Midday",
    "NOSE": "Face part",
    "NOTE": "Written message",
    "OKAY": "All right",
    "ONCE": "One time",
    "ONLY": "Sole",
    "ONTO": "Upon",
    "OPEN": "Not closed",
    "OVEN": "Baking appliance",
    "OVER": "Above",
    "PACE": "Speed",
    "PACK": "Bundle",
    "PAGE": "Paper sheet",
    "PAID": "Compensated",
    "PAIN": "Hurt",
    "PAIR": "Two",
    "PALM": "Hand center",
    "PARK": "Green area",
    "PART": "Piece",
    "PASS": "Go by",
    "PAST": "Before now",
    "PATH": "Trail",
    "PEAK": "Summit",
    "PICK": "Choose",
    "PLAN": "Strategy",
    "PLAY": "Game",
    "PLUS": "Addition",
    "POEM": "Verse",
    "POET": "Verse writer",
    "POLL": "Survey",
    "POOL": "Swimming area",
    "POOR": "Not rich",
    "POPE": "Catholic leader",
    "PORT": "Harbor",
    "POST": "Mail",
    "POUR": "Flow liquid",
    "PRAY": "Worship",
    "PULL": "Tug",
    "PURE": "Clean",
    "PUSH": "Shove",
    "QUIT": "Stop",
    "RACE": "Competition",
    "RAIN": "Precipitation",
    "RANK": "Position",
    "RARE": "Uncommon",
    "RATE": "Speed",
    "READ": "Look at text",
    "REAL": "True",
    "REAR": "Back",
    "RENT": "Lease payment",
    "REST": "Relax",
    "RICE": "Grain",
    "RICH": "Wealthy",
    "RIDE": "Travel",
    "RING": "Circle",
    "RISE": "Go up",
    "RISK": "Danger",
    "ROAD": "Street",
    "ROCK": "Stone",
    "ROLE": "Part",
    "ROLL": "Rotate",
    "ROOF": "House top",
    "ROOM": "Space",
    "ROOT": "Plant base",
    "ROSE": "Flower",
    "RULE": "Regulation",
    "RUNS": "Moves fast",
    "RUSH": "Hurry",
    "SAFE": "Secure",
    "SAID": "Spoke",
    "SAKE": "Purpose",
    "SALE": "Discount event",
    "SALT": "Seasoning",
    "SAME": "Identical",
    "SAND": "Beach material",
    "SAVE": "Rescue",
    "SEAT": "Chair",
    "SEEK": "Search for",
    "SEEM": "Appear",
    "SEEN": "Viewed",
    "SELF": "Oneself",
    "SELL": "Vend",
    "SEND": "Mail",
    "SENT": "Dispatched",
    "SHIP": "Water vessel",
    "SHOP": "Store",
    "SHOT": "Fired",
    "SHOW": "Display",
    "SHUT": "Close",
    "SICK": "Ill",
    "SIDE": "Edge",
    "SIGN": "Symbol",
    "SITE": "Location",
    "SIZE": "Dimension",
    "SKIN": "Body covering",
    "SLIP": "Slide",
    "SLOW": "Not fast",
    "SNOW": "Frozen precipitation",
    "SOFT": "Not hard",
    "SOIL": "Dirt",
    "SOLD": "Vended",
    "SOLE": "Only",
    "SOME": "A few",
    "SONG": "Musical piece",
    "SOON": "Shortly",
    "SORT": "Type",
    "SOUL": "Spirit",
    "SPOT": "Location",
    "STAR": "Celestial body",
    "STAY": "Remain",
    "STEP": "Pace",
    "STOP": "Cease",
    "SUCH": "Of that kind",
    "SUIT": "Business attire",
    "SURE": "Certain",
    "SWIM": "Water activity",
    "TAIL": "Rear appendage",
    "TAKE": "Grab",
    "TALE": "Story",
    "TALK": "Speak",
    "TALL": "High",
    "TANK": "Container",
    "TAPE": "Adhesive strip",
    "TASK": "Job",
    "TEAM": "Group",
    "TELL": "Inform",
    "TEND": "Care for",
    "TERM": "Word",
    "TEST": "Exam",
    "TEXT": "Written words",
    "THAN": "Comparison word",
    "THAT": "This thing",
    "THEM": "Those people",
    "THEN": "After that",
    "THEY": "Those people",
    "THIN": "Not thick",
    "THIS": "Current",
    "THUS": "Therefore",
    "TIDE": "Ocean movement",
    "TIED": "Fastened",
    "TILL": "Until",
    "TIME": "Duration",
    "TINY": "Very small",
    "TIPS": "Advice",
    "TIRE": "Wheel rubber",
    "TOLD": "Informed",
    "TONE": "Sound quality",
    "TOOK": "Grabbed",
    "TOOL": "Implement",
    "TOPS": "Best",
    "TOUR": "Trip",
    "TOWN": "Small city",
    "TREE": "Woody plant",
    "TRIP": "Journey",
    "TRUE": "Not false",
    "TUBE": "Cylinder",
    "TURN": "Rotate",
    "TYPE": "Kind",
    "UNIT": "Single item",
    "UPON": "On top of",
    "USED": "Utilized",
    "USER": "One who uses",
    "VARY": "Change",
    "VAST": "Huge",
    "VERB": "Action word",
    "VERY": "Extremely",
    "VIEW": "Sight",
    "VOTE": "Election choice",
    "WAGE": "Pay",
    "WAIT": "Stay",
    "WAKE": "Stop sleeping",
    "WALK": "Stroll",
    "WALL": "Room divider",
    "WANT": "Desire",
    "WARM": "Slightly hot",
    "WARN": "Alert",
    "WASH": "Clean",
    "WAVE": "Ocean motion",
    "WAYS": "Methods",
    "WEAK": "Not strong",
    "WEAR": "Put on",
    "WEEK": "Seven days",
    "WELL": "Good",
    "WENT": "Traveled",
    "WERE": "Past plural of be",
    "WEST": "Direction",
    "WHAT": "Which thing",
    "WHEN": "At what time",
    "WIDE": "Broad",
    "WIFE": "Married woman",
    "WILD": "Untamed",
    "WILL": "Going to",
    "WIND": "Air movement",
    "WINE": "Grape drink",
    "WING": "Bird part",
    "WIRE": "Metal strand",
    "WISE": "Smart",
    "WISH": "Desire",
    "WITH": "Alongside",
    "WOKE": "Awakened",
    "WOLF": "Wild canine",
    "WOOD": "Tree material",
    "WORD": "Vocabulary unit",
    "WORE": "Had on",
    "WORK": "Job",
    "WRAP": "Cover",
    "YARD": "Lawn",
    "YEAH": "Yes",
    "YEAR": "12 months",
    "YOUR": "Belonging to you",
    "ZERO": "Nothing",
    "ZONE": "Area",
    # Common 5-letter words
    "ABOUT": "Concerning",
    "ABOVE": "Higher than",
    "ABUSE": "Misuse",
    "ACTOR": "Performer",
    "ADMIT": "Confess",
    "ADOPT": "Take in",
    "ADULT": "Grown-up",
    "AFTER": "Following",
    "AGAIN": "Once more",
    "AGENT": "Representative",
    "AGREE": "Concur",
    "AHEAD": "In front",
    "ALARM": "Warning",
    "ALBUM": "Collection",
    "ALIEN": "Foreigner",
    "ALIKE": "Similar",
    "ALIVE": "Living",
    "ALLOW": "Permit",
    "ALONE": "By oneself",
    "ALONG": "Beside",
    "ALTER": "Change",
    "AMONG": "Amid",
    "ANGEL": "Heavenly being",
    "ANGER": "Rage",
    "ANGLE": "Corner",
    "ANGRY": "Mad",
    "APART": "Separate",
    "APPLE": "Fruit",
    "APPLY": "Request",
    "ARENA": "Stadium",
    "ARGUE": "Debate",
    "ARISE": "Get up",
    "ARMED": "With weapons",
    "ARMOR": "Protection",
    "ARRAY": "Collection",
    "ARROW": "Pointed missile",
    "ASIDE": "To the side",
    "ASSET": "Resource",
    "AVOID": "Stay away from",
    "AWARD": "Prize",
    "AWARE": "Conscious",
    "BADLY": "Poorly",
    "BASIC": "Fundamental",
    "BASIS": "Foundation",
    "BEACH": "Shore",
    "BEGAN": "Started",
    "BEGIN": "Start",
    "BEING": "Existing",
    "BELOW": "Under",
    "BENCH": "Seat",
    "BIBLE": "Holy book",
    "BLACK": "Dark color",
    "BLADE": "Sharp edge",
    "BLAME": "Fault",
    "BLANK": "Empty",
    "BLAST": "Explosion",
    "BLAZE": "Fire",
    "BLEND": "Mix",
    "BLESS": "Make holy",
    "BLIND": "Cannot see",
    "BLOCK": "Cube",
    "BLOOD": "Red fluid",
    "BLOOM": "Flower",
    "BLOWN": "Wind-affected",
    "BOARD": "Plank",
    "BOAST": "Brag",
    "BONUS": "Extra payment",
    "BOOST": "Increase",
    "BOOTH": "Small enclosure",
    "BOUND": "Limit",
    "BRAIN": "Thinking organ",
    "BRAND": "Product name",
    "BRAVE": "Courageous",
    "BREAD": "Baked food",
    "BREAK": "Shatter",
    "BREED": "Reproduce",
    "BRICK": "Building block",
    "BRIDE": "Woman marrying",
    "BRIEF": "Short",
    "BRING": "Carry",
    "BROAD": "Wide",
    "BROKE": "Shattered",
    "BROWN": "Earth color",
    "BRUSH": "Cleaning tool",
    "BUILD": "Construct",
    "BUILT": "Constructed",
    "BUNCH": "Group",
    "BURST": "Explode",
    "BUYER": "Purchaser",
    "CABLE": "Wire rope",
    "CALIF": "Islamic leader",
    "CANAL": "Water channel",
    "CANDY": "Sweet treat",
    "CARGO": "Freight",
    "CARRY": "Transport",
    "CARVE": "Cut shape",
    "CATCH": "Grab",
    "CAUSE": "Reason",
    "CEASE": "Stop",
    "CHAIN": "Linked metal",
    "CHAIR": "Seat",
    "CHAOS": "Disorder",
    "CHARM": "Appeal",
    "CHART": "Graph",
    "CHASE": "Pursue",
    "CHEAP": "Inexpensive",
    "CHEAT": "Deceive",
    "CHECK": "Verify",
    "CHEEK": "Face part",
    "CHEER": "Applause",
    "CHEST": "Body part",
    "CHIEF": "Leader",
    "CHILD": "Young person",
    "CHINA": "Country",
    "CHORD": "Musical notes",
    "CHOSE": "Selected",
    "CHUNK": "Large piece",
    "CLAIM": "Assert",
    "CLASS": "Category",
    "CLEAN": "Not dirty",
    "CLEAR": "Obvious",
    "CLERK": "Office worker",
    "CLICK": "Computer action",
    "CLIMB": "Ascend",
    "CLING": "Hold tight",
    "CLOCK": "Time device",
    "CLOSE": "Near",
    "CLOTH": "Fabric",
    "CLOUD": "Sky formation",
    "COACH": "Trainer",
    "COAST": "Shore",
    "COUCH": "Sofa",
    "COULD": "Was able",
    "COUNT": "Number",
    "COURT": "Legal place",
    "COVER": "Lid",
    "CRACK": "Split",
    "CRAFT": "Skill",
    "CRASH": "Collision",
    "CRAZY": "Insane",
    "CREAM": "Dairy product",
    "CREEK": "Stream",
    "CRIME": "Offense",
    "CRISP": "Crunchy",
    "CROSS": "Intersection",
    "CROWD": "Large group",
    "CROWN": "Royal headpiece",
    "CRUDE": "Raw",
    "CRUEL": "Mean",
    "CRUSH": "Squash",
    "CURVE": "Bend",
    "CYCLE": "Rotation",
    "DAILY": "Every day",
    "DAIRY": "Milk products",
    "DANCE": "Move to music",
    "DATED": "Old-fashioned",
    "DEALT": "Distributed",
    "DEATH": "End of life",
    "DEBUT": "First appearance",
    "DECAY": "Rot",
    "DELAY": "Postpone",
    "DENSE": "Thick",
    "DEPTH": "Deepness",
    "DEVIL": "Evil spirit",
    "DIARY": "Journal",
    "DIRTY": "Not clean",
    "DOUBT": "Uncertainty",
    "DOZEN": "Twelve",
    "DRAFT": "Rough version",
    "DRAIN": "Empty",
    "DRAMA": "Play",
    "DRANK": "Consumed liquid",
    "DRAWN": "Sketched",
    "DREAM": "Sleep vision",
    "DRESS": "Clothing",
    "DRIED": "Without moisture",
    "DRILL": "Tool",
    "DRINK": "Beverage",
    "DRIVE": "Operate vehicle",
    "DROIT": "Legal right",
    "DROVE": "Operated vehicle",
    "DROWN": "Suffocate in water",
    "DRUNK": "Intoxicated",
    "DWARF": "Small person",
    "DYING": "Near death",
    "EAGER": "Enthusiastic",
    "EARLY": "Before time",
    "EARTH": "Planet",
    "EATEN": "Consumed",
    "EIGHT": "Number",
    "ELDER": "Older person",
    "ELECT": "Choose",
    "ELITE": "Best",
    "EMERY": "Abrasive",
    "EMPTY": "Not full",
    "ENEMY": "Foe",
    "ENJOY": "Like",
    "ENTER": "Go in",
    "ENTRY": "Entrance",
    "EQUAL": "Same",
    "EQUIP": "Supply",
    "ERROR": "Mistake",
    "ESSAY": "Written work",
    "EVENT": "Occurrence",
    "EVERY": "Each",
    "EXACT": "Precise",
    "EXIST": "Be real",
    "EXTRA": "Additional",
    "FAINT": "Weak",
    "FAITH": "Belief",
    "FALSE": "Not true",
    "FAULT": "Defect",
    "FAVOR": "Support",
    "FEAST": "Big meal",
    "FENCE": "Barrier",
    "FEWER": "Less",
    "FIBER": "Thread",
    "FIELD": "Open land",
    "FIFTH": "Number",
    "FIFTY": "Number",
    "FIGHT": "Battle",
    "FINAL": "Last",
    "FIRST": "Before all",
    "FIXED": "Repaired",
    "FLAME": "Fire",
    "FLASH": "Quick light",
    "FLESH": "Body tissue",
    "FLOAT": "Stay on water",
    "FLOOD": "Water overflow",
    "FLOOR": "Room bottom",
    "FLOUR": "Baking powder",
    "FLUID": "Liquid",
    "FLUSH": "Rinse",
    "FOCUS": "Center",
    "FOGGY": "Misty",
    "FORCE": "Power",
    "FORGE": "Create",
    "FORTH": "Forward",
    "FORTY": "Number",
    "FORUM": "Discussion place",
    "FOUND": "Discovered",
    "FRAME": "Border",
    "FRANK": "Honest",
    "FRAUD": "Deception",
    "FRESH": "New",
    "FRONT": "Forward side",
    "FROST": "Frozen dew",
    "FRUIT": "Plant product",
    "FULLY": "Completely",
    "FUNNY": "Humorous",
    "GIANT": "Very large",
    "GIVEN": "Presented",
    "GLASS": "Transparent material",
    "GLOBE": "Sphere",
    "GLORY": "Fame",
    "GOING": "Moving",
    "GRACE": "Elegance",
    "GRADE": "Level",
    "GRAIN": "Cereal",
    "GRAND": "Great",
    "GRANT": "Give",
    "GRAPE": "Fruit",
    "GRASP": "Hold",
    "GRASS": "Lawn plant",
    "GRAVE": "Burial place",
    "GREAT": "Excellent",
    "GREEN": "Color",
    "GREET": "Welcome",
    "GRIEF": "Sadness",
    "GRILL": "Cooking device",
    "GRIND": "Crush",
    "GROSS": "Total",
    "GROUP": "Collection",
    "GROVE": "Small forest",
    "GROWN": "Matured",
    "GUARD": "Protector",
    "GUESS": "Estimate",
    "GUEST": "Visitor",
    "GUIDE": "Leader",
    "GUILT": "Fault",
    "HABIT": "Routine",
    "HANDS": "Body parts",
    "HANDY": "Useful",
    "HAPPY": "Joyful",
    "HARSH": "Severe",
    "HASN'T": "Has not",
    "HASTE": "Hurry",
    "HAVEN": "Safe place",
    "HEART": "Organ",
    "HEAVY": "Weighty",
    "HELLO": "Greeting",
    "HENCE": "Therefore",
    "HERBS": "Plants",
    "HIRED": "Employed",
    "HOBBY": "Pastime",
    "HONEY": "Sweet liquid",
    "HONOR": "Respect",
    "HORSE": "Animal",
    "HOTEL": "Lodging",
    "HOUND": "Dog type",
    "HOUSE": "Home",
    "HUMAN": "Person",
    "HUMOR": "Comedy",
    "HURRY": "Rush",
    "IDEAL": "Perfect",
    "IMAGE": "Picture",
    "IMPLY": "Suggest",
    "INDEX": "List",
    "INDIA": "Country",
    "INNER": "Inside",
    "INPUT": "Data entry",
    "IRONY": "Sarcasm",
    "ISSUE": "Problem",
    "ITEMS": "Things",
    "JAPAN": "Country",
    "JEANS": "Pants",
    "JOINT": "Connection",
    "JONES": "Common name",
    "JUDGE": "Arbiter",
    "JUICE": "Drink",
    "KEEPS": "Retains",
    "KNIFE": "Cutting tool",
    "KNOCK": "Hit",
    "KNOWN": "Familiar",
    "LABEL": "Tag",
    "LABOR": "Work",
    "LARGE": "Big",
    "LASER": "Light beam",
    "LATER": "After",
    "LATIN": "Language",
    "LAUGH": "Chuckle",
    "LAYER": "Level",
    "LEARN": "Study",
    "LEASE": "Rental",
    "LEAST": "Minimum",
    "LEAVE": "Depart",
    "LEGAL": "Lawful",
    "LEMON": "Citrus fruit",
    "LEVEL": "Flat",
    "LEVER": "Simple machine",
    "LIGHT": "Illumination",
    "LIKED": "Enjoyed",
    "LIMIT": "Boundary",
    "LINKS": "Connections",
    "LIONS": "Big cats",
    "LISTS": "Catalogs",
    "LIVED": "Resided",
    "LIVER": "Organ",
    "LIVES": "Exists",
    "LOCAL": "Nearby",
    "LODGE": "Cabin",
    "LOGIC": "Reasoning",
    "LOOSE": "Not tight",
    "LORDS": "Nobles",
    "LOVER": "Partner",
    "LOWER": "Reduce",
    "LOYAL": "Faithful",
    "LUCKY": "Fortunate",
    "LUNCH": "Midday meal",
    "LYING": "Not truthful",
    "MAGIC": "Illusion",
    "MAJOR": "Significant",
    "MAKER": "Creator",
    "MANOR": "Estate",
    "MARCH": "Walk",
    "MARRY": "Wed",
    "MATCH": "Contest",
    "MAYOR": "City leader",
    "MEANS": "Methods",
    "MEANT": "Intended",
    "MEDAL": "Award",
    "MEDIA": "News outlets",
    "MELON": "Fruit",
    "MERCY": "Forgiveness",
    "MERGE": "Combine",
    "MERIT": "Worth",
    "MERRY": "Joyful",
    "METAL": "Material",
    "METER": "Unit",
    "MIDST": "Middle",
    "MIGHT": "Power",
    "MINER": "Digger",
    "MINOR": "Small",
    "MINUS": "Less",
    "MIXED": "Combined",
    "MODEL": "Example",
    "MOIST": "Slightly wet",
    "MONEY": "Currency",
    "MONTH": "Time period",
    "MORAL": "Ethical",
    "MOTOR": "Engine",
    "MOUNT": "Climb",
    "MOUSE": "Small rodent",
    "MOUTH": "Face opening",
    "MOVED": "Changed position",
    "MOVIE": "Film",
    "MUSIC": "Melodies",
    "NAKED": "Unclothed",
    "NAMED": "Called",
    "NAMES": "Titles",
    "NAVAL": "Navy-related",
    "NEEDS": "Requires",
    "NERVE": "Body part",
    "NEVER": "Not ever",
    "NEWLY": "Recently",
    "NIGHT": "Dark time",
    "NINTH": "Number",
    "NOISE": "Sound",
    "NORTH": "Direction",
    "NOTED": "Famous",
    "NOTES": "Written records",
    "NOVEL": "Book",
    "NURSE": "Medical worker",
    "OCCUR": "Happen",
    "OCEAN": "Large water body",
    "OFFER": "Present",
    "OFTEN": "Frequently",
    "OLDER": "More aged",
    "OLIVE": "Green fruit",
    "ONION": "Vegetable",
    "OPENS": "Unlocks",
    "OPERA": "Musical drama",
    "ORBIT": "Path",
    "ORDER": "Arrangement",
    "ORGAN": "Body part",
    "OTHER": "Different",
    "OUGHT": "Should",
    "OUTER": "External",
    "OWNED": "Possessed",
    "OWNER": "Possessor",
    "OXIDE": "Chemical compound",
    "PAINT": "Color coating",
    "PAIRS": "Twos",
    "PANEL": "Board",
    "PANIC": "Fear",
    "PAPER": "Writing material",
    "PARTY": "Celebration",
    "PASTA": "Italian food",
    "PATCH": "Small piece",
    "PAUSE": "Stop briefly",
    "PEACE": "Calm",
    "PEARL": "Gem",
    "PENNY": "Coin",
    "PHASE": "Stage",
    "PHONE": "Telephone",
    "PHOTO": "Picture",
    "PIANO": "Instrument",
    "PIECE": "Part",
    "PILOT": "Flyer",
    "PITCH": "Throw",
    "PIXEL": "Screen dot",
    "PLACE": "Location",
    "PLAIN": "Simple",
    "PLANE": "Aircraft",
    "PLANT": "Flora",
    "PLATE": "Dish",
    "PLAZA": "Square",
    "PLEAD": "Beg",
    "PLAZA": "Public square",
    "POINT": "Tip",
    "POLAR": "Arctic",
    "POLLS": "Surveys",
    "POUCH": "Bag",
    "POUND": "Weight unit",
    "POWER": "Strength",
    "PRESS": "Push",
    "PRICE": "Cost",
    "PRIDE": "Self-respect",
    "PRIME": "First",
    "PRINT": "Text",
    "PRIOR": "Before",
    "PRIZE": "Award",
    "PROBE": "Investigate",
    "PROOF": "Evidence",
    "PROUD": "Self-satisfied",
    "PROVE": "Demonstrate",
    "PUPIL": "Student",
    "QUEEN": "Female monarch",
    "QUEST": "Search",
    "QUICK": "Fast",
    "QUIET": "Silent",
    "QUITE": "Very",
    "QUOTE": "Citation",
    "RADAR": "Detection system",
    "RADIO": "Broadcast",
    "RAISE": "Lift",
    "RANCH": "Farm",
    "RANGE": "Scope",
    "RAPID": "Fast",
    "RATIO": "Proportion",
    "REACH": "Extend to",
    "REACT": "Respond",
    "READS": "Looks at text",
    "READY": "Prepared",
    "REALM": "Kingdom",
    "REBEL": "Resist",
    "REFER": "Direct",
    "REIGN": "Rule",
    "RELAX": "Rest",
    "RELAY": "Pass on",
    "REPLY": "Respond",
    "RIDER": "One who rides",
    "RIDGE": "Mountain top",
    "RIFLE": "Gun",
    "RIGHT": "Correct",
    "RIGID": "Stiff",
    "RISKY": "Dangerous",
    "RIVAL": "Competitor",
    "RIVER": "Water body",
    "ROAST": "Cook",
    "ROBOT": "Machine",
    "ROGER": "Name",
    "ROMAN": "Of Rome",
    "ROOTS": "Plant bases",
    "ROUGH": "Not smooth",
    "ROUND": "Circular",
    "ROUTE": "Path",
    "ROYAL": "Regal",
    "RUGBY": "Sport",
    "RULED": "Governed",
    "RULER": "Leader",
    "RULES": "Regulations",
    "RURAL": "Countryside",
    "SADLY": "Unfortunately",
    "SAINT": "Holy person",
    "SALAD": "Vegetable dish",
    "SALES": "Selling",
    "SANDY": "With sand",
    "SANTA": "Christmas figure",
    "SAUCE": "Condiment",
    "SAVED": "Rescued",
    "SCALE": "Measurement",
    "SCARY": "Frightening",
    "SCENE": "Setting",
    "SCENT": "Smell",
    "SCOPE": "Range",
    "SCORE": "Points",
    "SCOUT": "Explorer",
    "SCREW": "Fastener",
    "SEIZE": "Grab",
    "SENSE": "Feeling",
    "SERVE": "Help",
    "SETUP": "Arrangement",
    "SEVEN": "Number",
    "SHADE": "Shadow",
    "SHAFT": "Pole",
    "SHAKE": "Tremble",
    "SHALL": "Will",
    "SHAME": "Disgrace",
    "SHAPE": "Form",
    "SHARE": "Divide",
    "SHARK": "Fish",
    "SHARP": "Pointed",
    "SHEEP": "Farm animal",
    "SHEER": "Pure",
    "SHEET": "Flat material",
    "SHELF": "Storage",
    "SHELL": "Hard covering",
    "SHIFT": "Change",
    "SHINE": "Glow",
    "SHIRT": "Clothing",
    "SHOCK": "Surprise",
    "SHOES": "Footwear",
    "SHOOK": "Trembled",
    "SHOOT": "Fire",
    "SHORE": "Beach",
    "SHORT": "Not tall",
    "SHOUT": "Yell",
    "SHOWN": "Displayed",
    "SIDED": "Took sides",
    "SIGHT": "Vision",
    "SIGNS": "Symbols",
    "SILLY": "Foolish",
    "SINCE": "Because",
    "SIXTH": "Number",
    "SIXTY": "Number",
    "SIZED": "Measured",
    "SIZES": "Dimensions",
    "SKILL": "Ability",
    "SKULL": "Head bone",
    "SLASH": "Cut",
    "SLATE": "Rock",
    "SLAVE": "Captive",
    "SLEEP": "Rest",
    "SLICE": "Piece",
    "SLIDE": "Glide",
    "SLOPE": "Incline",
    "SMALL": "Little",
    "SMART": "Intelligent",
    "SMELL": "Odor",
    "SMILE": "Grin",
    "SMITH": "Metalworker",
    "SMOKE": "Vapor",
    "SNAKE": "Reptile",
    "SOLAR": "Sun-related",
    "SOLID": "Firm",
    "SOLVE": "Figure out",
    "SORRY": "Apologetic",
    "SORTS": "Types",
    "SOULS": "Spirits",
    "SOUND": "Noise",
    "SOUTH": "Direction",
    "SPACE": "Area",
    "SPARE": "Extra",
    "SPARK": "Flash",
    "SPEAK": "Talk",
    "SPEED": "Velocity",
    "SPELL": "Magic words",
    "SPEND": "Use money",
    "SPENT": "Used money",
    "SPICE": "Flavoring",
    "SPILL": "Overflow",
    "SPINE": "Backbone",
    "SPLIT": "Divide",
    "SPOKE": "Said",
    "SPORT": "Game",
    "SPOTS": "Locations",
    "SPRAY": "Mist",
    "SQUAD": "Team",
    "STACK": "Pile",
    "STAFF": "Workers",
    "STAGE": "Platform",
    "STAIN": "Mark",
    "STAIR": "Step",
    "STAKE": "Bet",
    "STAMP": "Mark",
    "STAND": "Be upright",
    "STARK": "Bare",
    "START": "Begin",
    "STATE": "Condition",
    "STAYS": "Remains",
    "STEAM": "Water vapor",
    "STEEL": "Metal",
    "STEEP": "Sharply inclined",
    "STEER": "Guide",
    "STEMS": "Plant parts",
    "STEPS": "Stairs",
    "STERN": "Strict",
    "STICK": "Thin branch",
    "STIFF": "Rigid",
    "STILL": "Not moving",
    "STOCK": "Supply",
    "STOLE": "Took wrongly",
    "STONE": "Rock",
    "STOOD": "Was upright",
    "STOOL": "Seat",
    "STOPS": "Halts",
    "STORE": "Shop",
    "STORM": "Bad weather",
    "STORY": "Tale",
    "STOVE": "Cooking device",
    "STRAP": "Band",
    "STRAW": "Dried grass",
    "STRIP": "Remove",
    "STUCK": "Attached",
    "STUDY": "Learn",
    "STUFF": "Things",
    "STYLE": "Fashion",
    "SUGAR": "Sweetener",
    "SUITE": "Room set",
    "SUNNY": "Bright",
    "SUPER": "Great",
    "SURGE": "Rush",
    "SWAMP": "Wetland",
    "SWEAR": "Promise",
    "SWEAT": "Perspiration",
    "SWEET": "Sugary",
    "SWEPT": "Cleaned",
    "SWIFT": "Fast",
    "SWING": "Move back and forth",
    "SWORD": "Weapon",
    "SWORE": "Promised",
    "SWORN": "Vowed",
    "TABLE": "Furniture",
    "TAKEN": "Grabbed",
    "TAKES": "Grabs",
    "TALKS": "Speaks",
    "TASTE": "Flavor",
    "TAXES": "Government fees",
    "TEACH": "Instruct",
    "TEAMS": "Groups",
    "TEARS": "Eye drops",
    "TEETH": "Mouth bones",
    "TELLS": "Informs",
    "TEMPO": "Speed",
    "TENDS": "Cares for",
    "TERMS": "Conditions",
    "TESTS": "Exams",
    "TEXAS": "State",
    "THANK": "Express gratitude",
    "THEFT": "Stealing",
    "THEIR": "Belonging to them",
    "THEME": "Topic",
    "THERE": "That place",
    "THESE": "These things",
    "THICK": "Not thin",
    "THIEF": "Robber",
    "THING": "Object",
    "THINK": "Ponder",
    "THIRD": "After second",
    "THOSE": "Those things",
    "THREE": "Number",
    "THREW": "Tossed",
    "THROW": "Toss",
    "THUMB": "Finger",
    "TIGER": "Big cat",
    "TIGHT": "Snug",
    "TIRED": "Exhausted",
    "TITLE": "Name",
    "TODAY": "This day",
    "TOKEN": "Symbol",
    "TOLLS": "Fees",
    "TONES": "Sounds",
    "TOPIC": "Subject",
    "TORCH": "Light",
    "TOTAL": "Sum",
    "TOUCH": "Feel",
    "TOUGH": "Hard",
    "TOWER": "Tall building",
    "TOWNS": "Small cities",
    "TOXIC": "Poisonous",
    "TRACE": "Track",
    "TRACK": "Path",
    "TRADE": "Exchange",
    "TRAIL": "Path",
    "TRAIN": "Railway vehicle",
    "TRAIT": "Characteristic",
    "TRASH": "Garbage",
    "TREAT": "Gift",
    "TREES": "Plants",
    "TREND": "Fashion",
    "TRIAL": "Test",
    "TRIBE": "Group",
    "TRICK": "Prank",
    "TRIED": "Attempted",
    "TRIES": "Attempts",
    "TRIPS": "Journeys",
    "TROOP": "Group",
    "TRUCK": "Vehicle",
    "TRULY": "Really",
    "TRUMP": "Beat",
    "TRUNK": "Tree part",
    "TRUST": "Faith",
    "TRUTH": "Fact",
    "TUBES": "Cylinders",
    "TURNS": "Rotates",
    "TWICE": "Two times",
    "TWINS": "Two siblings",
    "TWIST": "Turn",
    "TYPED": "Keyed in",
    "TYPES": "Kinds",
    "UNCLE": "Relative",
    "UNDER": "Below",
    "UNION": "Organization",
    "UNITE": "Join",
    "UNITS": "Items",
    "UNITY": "Togetherness",
    "UNTIL": "Up to",
    "UPPER": "Higher",
    "UPSET": "Disturbed",
    "URBAN": "City-related",
    "URGES": "Encourages",
    "USAGE": "Use",
    "USUAL": "Normal",
    "VALID": "Legal",
    "VALUE": "Worth",
    "VALVE": "Flow control",
    "VAPOR": "Gas",
    "VAULT": "Safe",
    "VENUE": "Location",
    "VERSE": "Poetry",
    "VIDEO": "Recording",
    "VIEWS": "Opinions",
    "VILLA": "House",
    "VIRUS": "Germ",
    "VISIT": "Go see",
    "VITAL": "Essential",
    "VIVID": "Bright",
    "VOCAL": "Voice-related",
    "VOICE": "Sound",
    "VOTER": "One who votes",
    "VOTES": "Ballots",
    "WAGES": "Pay",
    "WAGON": "Cart",
    "WAIST": "Body part",
    "WALKS": "Strolls",
    "WALLS": "Barriers",
    "WANTS": "Desires",
    "WASTE": "Trash",
    "WATCH": "Timepiece",
    "WATER": "H2O",
    "WAVES": "Ocean motions",
    "WEEKS": "Time periods",
    "WEIGH": "Measure weight",
    "WEIRD": "Strange",
    "WELLS": "Water sources",
    "WHALE": "Large mammal",
    "WHEAT": "Grain",
    "WHEEL": "Circular object",
    "WHERE": "What place",
    "WHICH": "What one",
    "WHILE": "During",
    "WHITE": "Color",
    "WHOLE": "Complete",
    "WHOSE": "Belonging to whom",
    "WIDER": "More broad",
    "WIDTH": "Breadth",
    "WINES": "Drinks",
    "WINGS": "Flying parts",
    "WIRES": "Metal strands",
    "WITCH": "Sorceress",
    "WIVES": "Married women",
    "WOKEN": "Awakened",
    "WOMAN": "Adult female",
    "WOMEN": "Adult females",
    "WOODS": "Forest",
    "WORDS": "Vocabulary",
    "WORKS": "Functions",
    "WORLD": "Earth",
    "WORRY": "Fret",
    "WORSE": "More bad",
    "WORST": "Most bad",
    "WORTH": "Value",
    "WOULD": "Conditional",
    "WOUND": "Injury",
    "WRAP": "Cover",
    "WRIST": "Body part",
    "WRITE": "Put pen to paper",
    "WRONG": "Incorrect",
    "WROTE": "Authored",
    "YARDS": "Lawns",
    "YEARS": "Time periods",
    "YIELD": "Produce",
    "YOUNG": "Not old",
    "YOURS": "Belonging to you",
    "YOUTH": "Young person",
    "ZONES": "Areas",
}


def get_clue_for_word(word: str) -> str:
    """Get a clue for a word, using templates or generating a simple one."""
    word_upper = word.upper()
    if word_upper in CLUE_TEMPLATES:
        return CLUE_TEMPLATES[word_upper]
    # Default clue
    return f"{len(word)}-letter word"


def load_dictionary_words(db: Session) -> dict[int, set[str]]:
    """Load all dictionary words grouped by length."""
    words_by_length: dict[int, set[str]] = {}

    words = db.query(DictionaryWord.word, DictionaryWord.length).all()
    for word, length in words:
        if length not in words_by_length:
            words_by_length[length] = set()
        words_by_length[length].add(word.upper())

    logger.info(f"Loaded {sum(len(w) for w in words_by_length.values())} dictionary words")
    return words_by_length


def extract_word_slots(pattern: list[list[str]]) -> list[dict]:
    """Extract word slots from a pattern grid."""
    size = len(pattern)
    slots = []
    clue_num = 1

    for r in range(size):
        for c in range(size):
            if pattern[r][c] == BLACK:
                continue

            # Check if this cell starts an across word
            starts_across = (c == 0 or pattern[r][c-1] == BLACK) and \
                           (c + 1 < size and pattern[r][c+1] != BLACK)

            # Check if this cell starts a down word
            starts_down = (r == 0 or pattern[r-1][c] == BLACK) and \
                         (r + 1 < size and pattern[r+1][c] != BLACK)

            if starts_across or starts_down:
                if starts_across:
                    # Calculate length
                    length = 0
                    cc = c
                    while cc < size and pattern[r][cc] != BLACK:
                        length += 1
                        cc += 1
                    if length >= 3:  # Only include 3+ letter words
                        slots.append({
                            "number": clue_num,
                            "direction": "across",
                            "row": r,
                            "col": c,
                            "length": length,
                            "cells": [(r, c + i) for i in range(length)],
                        })

                if starts_down:
                    # Calculate length
                    length = 0
                    rr = r
                    while rr < size and pattern[rr][c] != BLACK:
                        length += 1
                        rr += 1
                    if length >= 3:  # Only include 3+ letter words
                        slots.append({
                            "number": clue_num,
                            "direction": "down",
                            "row": r,
                            "col": c,
                            "length": length,
                            "cells": [(r + i, c) for i in range(length)],
                        })

                if starts_across or starts_down:
                    clue_num += 1

    return slots


def get_pattern_for_slot(solution: list[list[str]], slot: dict) -> list[Optional[str]]:
    """Get current letter constraints for a slot."""
    pattern = []
    for r, c in slot["cells"]:
        cell = solution[r][c]
        if cell == "." or cell == BLACK:
            pattern.append(None)
        else:
            pattern.append(cell)
    return pattern


def matches_pattern(word: str, pattern: list[Optional[str]]) -> bool:
    """Check if word matches the pattern constraints."""
    if len(word) != len(pattern):
        return False
    for i, char in enumerate(pattern):
        if char is not None and word[i] != char:
            return False
    return True


def fill_puzzle_with_backtracking(
    pattern: list[list[str]],
    slots: list[dict],
    words_by_length: dict[int, set[str]],
    max_attempts: int = 50000
) -> Optional[list[list[str]]]:
    """Fill a puzzle pattern with valid words using backtracking."""
    size = len(pattern)
    solution = [row[:] for row in pattern]  # Copy pattern

    used_words: set[str] = set()
    backtrack_count = [0]  # Use list to allow modification in nested function
    filled_slots: list[int] = []  # Track which slots have been filled

    def count_constraints(slot: dict) -> int:
        """Count how many cells already have letters."""
        count = 0
        for r, c in slot["cells"]:
            if solution[r][c] not in (".", BLACK):
                count += 1
        return count

    def get_candidates_for_slot(slot: dict) -> list[str]:
        """Get candidate words that match current constraints."""
        length = slot["length"]
        if length not in words_by_length:
            return []

        current_pattern = get_pattern_for_slot(solution, slot)
        candidates = [w for w in words_by_length[length]
                     if matches_pattern(w, current_pattern) and w not in used_words]
        return candidates

    def get_next_slot(remaining_slots: list[int]) -> Optional[int]:
        """Choose the most constrained slot (fewest valid candidates)."""
        if not remaining_slots:
            return None

        best_slot = None
        best_count = float('inf')

        for idx in remaining_slots:
            slot = slots[idx]
            candidates = get_candidates_for_slot(slot)
            count = len(candidates)

            if count == 0:
                return None  # Dead end - no valid words for this slot

            if count < best_count:
                best_count = count
                best_slot = idx

        return best_slot

    def try_fill(remaining_slots: list[int]) -> bool:
        if not remaining_slots:
            return True  # All slots filled!

        if backtrack_count[0] >= max_attempts:
            return False

        # Choose most constrained slot
        slot_idx = get_next_slot(remaining_slots)
        if slot_idx is None:
            return False  # Dead end

        slot = slots[slot_idx]
        candidates = get_candidates_for_slot(slot)

        # Shuffle for variety
        random.shuffle(candidates)

        for word in candidates[:500]:  # Try many candidates
            # Place the word
            old_values = []
            for i, (r, c) in enumerate(slot["cells"]):
                old_values.append(solution[r][c])
                solution[r][c] = word[i]
            used_words.add(word)

            # Try to fill remaining slots
            new_remaining = [i for i in remaining_slots if i != slot_idx]
            if try_fill(new_remaining):
                return True

            # Backtrack
            backtrack_count[0] += 1
            used_words.discard(word)
            for i, (r, c) in enumerate(slot["cells"]):
                solution[r][c] = old_values[i]

        return False

    # Start with all slots
    all_slot_indices = list(range(len(slots)))
    if try_fill(all_slot_indices):
        return solution
    return None


def generate_validated_puzzle(
    db: Session,
    pattern_idx: int = None,
    seed: int = None
) -> Optional[dict]:
    """
    Generate a single validated crossword puzzle.

    All words are verified against the dictionary database.
    """
    if seed is not None:
        random.seed(seed)

    # Load dictionary
    words_by_length = load_dictionary_words(db)

    if not words_by_length:
        logger.error("No dictionary words found!")
        return None

    # Select pattern
    if pattern_idx is not None:
        pattern = PATTERNS[pattern_idx % len(PATTERNS)]
    else:
        pattern = random.choice(PATTERNS)

    # Extract word slots
    slots = extract_word_slots(pattern)

    if not slots:
        logger.error("No word slots found in pattern!")
        return None

    logger.info(f"Pattern has {len(slots)} word slots")

    # Try to fill the puzzle
    solution = fill_puzzle_with_backtracking(pattern, slots, words_by_length)

    if solution is None:
        logger.warning("Failed to fill puzzle with valid words")
        return None

    # Verify all words are in dictionary
    for slot in slots:
        word = "".join(solution[r][c] for r, c in slot["cells"])
        if word not in words_by_length.get(len(word), set()):
            logger.error(f"Word '{word}' not in dictionary!")
            return None

    # Build clues
    clues_across = []
    clues_down = []

    for slot in slots:
        word = "".join(solution[r][c] for r, c in slot["cells"])
        clue = get_clue_for_word(word)

        clue_entry = {
            "number": slot["number"],
            "clue": clue,
            "length": slot["length"],
            "row": slot["row"],
            "col": slot["col"],
        }

        if slot["direction"] == "across":
            clues_across.append(clue_entry)
        else:
            clues_down.append(clue_entry)

    # Create empty grid for play (hide letters, show black squares)
    size = len(pattern)
    grid = [[" " if cell != BLACK else BLACK for cell in row] for row in solution]

    logger.info(f"Successfully generated puzzle with {len(slots)} words")

    return {
        "size": size,
        "solution": solution,
        "grid": grid,
        "clues_across": sorted(clues_across, key=lambda x: x["number"]),
        "clues_down": sorted(clues_down, key=lambda x: x["number"]),
    }


def generate_weekly_puzzles(db: Session, count: int = 7, week_seed: int = None) -> list[dict]:
    """
    Generate multiple validated puzzles for a week.

    Uses different patterns and seeds for variety.
    """
    puzzles = []

    for i in range(count):
        # Use different seed for each puzzle
        seed = (week_seed or 0) + i * 12345 if week_seed else None
        pattern_idx = i % len(PATTERNS)

        puzzle = generate_validated_puzzle(db, pattern_idx=pattern_idx, seed=seed)

        if puzzle:
            puzzles.append(puzzle)
            logger.info(f"Generated puzzle {i+1}/{count}")
        else:
            # Retry with different pattern
            for retry in range(3):
                alt_pattern = (pattern_idx + retry + 1) % len(PATTERNS)
                puzzle = generate_validated_puzzle(db, pattern_idx=alt_pattern, seed=seed)
                if puzzle:
                    puzzles.append(puzzle)
                    logger.info(f"Generated puzzle {i+1}/{count} (retry {retry+1})")
                    break
            else:
                logger.error(f"Failed to generate puzzle {i+1}/{count}")

    return puzzles


# Legacy function for compatibility
def get_random_templates(count: int, seed: int = None) -> list[dict]:
    """
    Legacy function - returns empty templates that will be filled dynamically.

    The actual puzzle generation now happens in puzzle_cache.py using
    generate_weekly_puzzles() which validates against the dictionary.
    """
    if seed is not None:
        random.seed(seed)

    templates = []
    for i in range(count):
        pattern = PATTERNS[i % len(PATTERNS)]
        size = len(pattern)

        # Return pattern structure - actual filling happens later
        templates.append({
            "size": size,
            "pattern": pattern,
            "solution": pattern,  # Will be filled by cache
            "clues_across": [],
            "clues_down": [],
        })

    return templates


def validate_all_templates(db=None) -> bool:
    """Validate that puzzle generation is working."""
    logger.info(f"Loaded {len(PATTERNS)} puzzle patterns")
    logger.info(f"Loaded {len(CLUE_TEMPLATES)} clue templates")
    return True
