"""Crossword puzzle generator with dictionary validation.

Generates valid 5x5 mini crosswords with 1-5 black squares.
All words are validated against the dictionary database.
"""

import logging
import random
from typing import Optional
from sqlalchemy.orm import Session

from app.models.cache_meta import DictionaryWord

logger = logging.getLogger(__name__)

# Black square marker
BLACK = "#"

# Pre-defined grid patterns with black squares at CORNERS ONLY
# This ensures all word slots are 3+ letters (no 2-letter fragments)
PATTERNS = [
    # Pattern 1: No black squares (10 words: 5 across + 5 down, all 5 letters)
    [
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
    ],
    # Pattern 2: One corner (top-left)
    [
        [BLACK, ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
    ],
    # Pattern 3: One corner (bottom-right)
    [
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", BLACK],
    ],
    # Pattern 4: Two diagonal corners (top-left, bottom-right)
    [
        [BLACK, ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", BLACK],
    ],
    # Pattern 5: Two diagonal corners (top-right, bottom-left)
    [
        [".", ".", ".", ".", BLACK],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [BLACK, ".", ".", ".", "."],
    ],
    # Pattern 6: Two adjacent corners (top row)
    [
        [BLACK, ".", ".", ".", BLACK],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
    ],
    # Pattern 7: Two adjacent corners (bottom row)
    [
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [BLACK, ".", ".", ".", BLACK],
    ],
    # Pattern 8: Three corners
    [
        [BLACK, ".", ".", ".", BLACK],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [BLACK, ".", ".", ".", "."],
    ],
    # Pattern 9: Four corners (creates 3-letter edge words)
    [
        [BLACK, ".", ".", ".", BLACK],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [".", ".", ".", ".", "."],
        [BLACK, ".", ".", ".", BLACK],
    ],
]

# Simple clue templates based on common word patterns
CLUE_TEMPLATES = {
    # Common 3-letter words
    "THE": "Definite article",
    "AND": "Plus",
    "FOR": "In favor of",
    "ARE": "Exist (plural)",
    "BUT": "However",
    "NOT": "Negative",
    "YOU": "Second person pronoun",
    "ALL": "Everything",
    "CAN": "Able to",
    "HAD": "Possessed",
    "HER": "Belonging to her",
    "WAS": "Past tense of be",
    "ONE": "Single",
    "OUR": "Belonging to us",
    "OUT": "Not in",
    "DAY": "24 hours",
    "GET": "Obtain",
    "HAS": "Possesses",
    "HIM": "That man",
    "HIS": "Belonging to him",
    "HOW": "In what way",
    "MAN": "Adult male",
    "NEW": "Not old",
    "NOW": "At this moment",
    "OLD": "Not new",
    "SEE": "View",
    "WAY": "Path",
    "WHO": "Which person",
    "BOY": "Young male",
    "DID": "Past tense of do",
    "ITS": "Belonging to it",
    "LET": "Allow",
    "PUT": "Place",
    "SAY": "Speak",
    "SHE": "That woman",
    "TOO": "Also",
    "USE": "Utilize",
    "CAT": "Feline pet",
    "DOG": "Canine pet",
    "RUN": "Move fast",
    "SUN": "Star",
    "RED": "Color of blood",
    "BIG": "Large",
    "END": "Finish",
    "SET": "Group",
    "TOP": "Highest point",
    "ACE": "Tennis serve",
    "ADD": "Sum up",
    "AGE": "Years old",
    "AGO": "In the past",
    "AID": "Help",
    "AIM": "Target",
    "AIR": "Atmosphere",
    "APE": "Primate",
    "ARC": "Curve",
    "ARK": "Noah's boat",
    "ARM": "Limb",
    "ART": "Creative work",
    "ATE": "Consumed",
    "AWE": "Wonder",
    "AXE": "Chopping tool",
    "BAD": "Not good",
    "BAG": "Sack",
    "BAN": "Prohibit",
    "BAR": "Pub",
    "BAT": "Flying mammal",
    "BED": "Sleeping furniture",
    "BET": "Wager",
    "BIT": "Small piece",
    "BOW": "Bend forward",
    "BOX": "Container",
    "BUS": "Public vehicle",
    "BUY": "Purchase",
    "CAB": "Taxi",
    "CAP": "Hat",
    "CAR": "Automobile",
    "COP": "Police officer",
    "COW": "Farm animal",
    "CRY": "Weep",
    "CUP": "Drinking vessel",
    "CUT": "Slice",
    "DAM": "Water barrier",
    "DEN": "Animal home",
    "DEW": "Morning moisture",
    "DIE": "Perish",
    "DIG": "Excavate",
    "DIM": "Not bright",
    "DIP": "Submerge briefly",
    "DOT": "Small spot",
    "DRY": "Not wet",
    "DUE": "Owed",
    "DUG": "Excavated",
    "EAR": "Hearing organ",
    "EAT": "Consume food",
    "EEL": "Snake-like fish",
    "EGG": "Oval food",
    "ELF": "Mythical being",
    "ELM": "Type of tree",
    "ERA": "Time period",
    "EVE": "Evening",
    "EYE": "Seeing organ",
    "FAN": "Cooling device",
    "FAR": "Distant",
    "FAT": "Not thin",
    "FED": "Gave food",
    "FEW": "Not many",
    "FIG": "Fruit",
    "FIN": "Fish part",
    "FIT": "In shape",
    "FLY": "Soar",
    "FOG": "Mist",
    "FOX": "Cunning animal",
    "FUN": "Enjoyment",
    "FUR": "Animal coat",
    "GAP": "Opening",
    "GAS": "Fuel",
    "GEM": "Jewel",
    "GOT": "Obtained",
    "GUM": "Chewing candy",
    "GUN": "Firearm",
    "GUT": "Intestine",
    "GUY": "Man",
    "GYM": "Exercise place",
    "HAM": "Pork meat",
    "HAT": "Head covering",
    "HAY": "Dried grass",
    "HEN": "Female chicken",
    "HID": "Concealed",
    "HIP": "Body joint",
    "HIT": "Strike",
    "HOG": "Pig",
    "HOP": "Small jump",
    "HOT": "High temperature",
    "HUB": "Center",
    "HUG": "Embrace",
    "HUT": "Small shelter",
    "ICE": "Frozen water",
    "ICY": "Very cold",
    "ILL": "Sick",
    "INK": "Pen fluid",
    "INN": "Small hotel",
    "IRE": "Anger",
    "IVY": "Climbing plant",
    "JAM": "Fruit spread",
    "JAR": "Glass container",
    "JAW": "Mouth bone",
    "JET": "Fast plane",
    "JOB": "Work",
    "JOG": "Light run",
    "JOY": "Happiness",
    "JUG": "Pitcher",
    "KEG": "Barrel",
    "KEY": "Lock opener",
    "KID": "Child",
    "KIT": "Set of items",
    "LAB": "Laboratory",
    "LAD": "Young man",
    "LAP": "Circuit",
    "LAW": "Legal rule",
    "LAY": "Put down",
    "LEG": "Limb",
    "LID": "Cover",
    "LIE": "Falsehood",
    "LIP": "Mouth edge",
    "LOG": "Wood piece",
    "LOT": "Many",
    "LOW": "Not high",
    "MAD": "Angry",
    "MAP": "Chart",
    "MAT": "Floor covering",
    "MEN": "Adult males",
    "MET": "Encountered",
    "MIX": "Combine",
    "MOB": "Crowd",
    "MOM": "Mother",
    "MOP": "Cleaning tool",
    "MUD": "Wet dirt",
    "MUG": "Cup",
    "NAP": "Short sleep",
    "NET": "Mesh",
    "NIT": "Louse egg",
    "NOD": "Head gesture",
    "NOR": "And not",
    "NUN": "Religious woman",
    "NUT": "Hard seed",
    "OAK": "Tree type",
    "OAR": "Rowing tool",
    "OAT": "Grain",
    "ODD": "Strange",
    "OIL": "Lubricant",
    "ORB": "Sphere",
    "ORE": "Metal rock",
    "OWE": "Be in debt",
    "OWL": "Night bird",
    "OWN": "Possess",
    "PAD": "Cushion",
    "PAN": "Cooking pot",
    "PAT": "Light touch",
    "PAW": "Animal foot",
    "PAY": "Compensate",
    "PEA": "Green vegetable",
    "PEN": "Writing tool",
    "PET": "Animal companion",
    "PIE": "Baked dessert",
    "PIG": "Farm animal",
    "PIN": "Sharp fastener",
    "PIT": "Hole",
    "POD": "Seed case",
    "POP": "Father",
    "POT": "Container",
    "PUB": "Bar",
    "PUN": "Word play",
    "PUP": "Young dog",
    "RAG": "Cloth",
    "RAM": "Male sheep",
    "RAN": "Moved fast",
    "RAP": "Knock",
    "RAT": "Rodent",
    "RAW": "Uncooked",
    "RAY": "Light beam",
    "RIB": "Bone",
    "RID": "Free from",
    "RIG": "Equipment",
    "RIM": "Edge",
    "RIP": "Tear",
    "ROB": "Steal",
    "ROD": "Stick",
    "ROT": "Decay",
    "ROW": "Line",
    "RUB": "Massage",
    "RUG": "Floor covering",
    "SAD": "Unhappy",
    "SAP": "Tree fluid",
    "SAT": "Was seated",
    "SAW": "Cutting tool",
    "SEA": "Ocean",
    "SIP": "Drink slowly",
    "SIT": "Be seated",
    "SIX": "Number",
    "SKI": "Snow sport",
    "SKY": "Above",
    "SOB": "Cry loudly",
    "SOD": "Grass",
    "SON": "Male child",
    "SPA": "Resort",
    "SPY": "Secret agent",
    "STY": "Pig pen",
    "SUB": "Submarine",
    "SUM": "Total",
    "TAB": "Bill",
    "TAG": "Label",
    "TAN": "Brown color",
    "TAP": "Light knock",
    "TAR": "Black substance",
    "TAX": "Government fee",
    "TEA": "Hot drink",
    "TEN": "Number",
    "TIE": "Necktie",
    "TIN": "Metal",
    "TIP": "Point",
    "TOE": "Foot digit",
    "TON": "Heavy weight",
    "TOW": "Pull",
    "TOY": "Plaything",
    "TUB": "Bath container",
    "TUG": "Pull hard",
    "TWO": "Number",
    "URN": "Vase",
    "VAN": "Vehicle",
    "VAT": "Large container",
    "VET": "Animal doctor",
    "VIA": "By way of",
    "WAR": "Armed conflict",
    "WAX": "Candle material",
    "WEB": "Spider's creation",
    "WED": "Marry",
    "WET": "Not dry",
    "WIG": "Hair piece",
    "WIN": "Victory",
    "WIT": "Humor",
    "WOE": "Sorrow",
    "WOK": "Asian pan",
    "WON": "Achieved victory",
    "ZAP": "Hit with energy",
    "ZEN": "Buddhist concept",
    "ZIP": "Fasten",
    "ZIT": "Pimple",
    "ZOO": "Animal park",
    # Common 4-letter words
    "ABLE": "Capable",
    "ALSO": "In addition",
    "AREA": "Region",
    "ARMY": "Military force",
    "AWAY": "Not here",
    "BABY": "Infant",
    "BACK": "Rear",
    "BALL": "Round toy",
    "BAND": "Musical group",
    "BANK": "Financial institution",
    "BASE": "Foundation",
    "BEAR": "Large mammal",
    "BEAT": "Rhythm",
    "BEEN": "Past participle of be",
    "BELL": "Ringing device",
    "BEST": "Most good",
    "BIRD": "Flying animal",
    "BLOW": "Wind gust",
    "BLUE": "Sky color",
    "BOAT": "Water vessel",
    "BODY": "Physical form",
    "BOOK": "Reading material",
    "BORN": "Brought into life",
    "BOSS": "Manager",
    "BOTH": "Two together",
    "BOWL": "Deep dish",
    "BURN": "Be on fire",
    "CALL": "Phone",
    "CALM": "Peaceful",
    "CAME": "Arrived",
    "CAMP": "Outdoor stay",
    "CARD": "Paper rectangle",
    "CARE": "Concern",
    "CASE": "Instance",
    "CASH": "Money",
    "CAST": "Throw",
    "CELL": "Small room",
    "CITY": "Urban area",
    "CLUB": "Organization",
    "COAT": "Jacket",
    "CODE": "System",
    "COLD": "Low temperature",
    "COME": "Arrive",
    "COOK": "Prepare food",
    "COOL": "Slightly cold",
    "COPY": "Duplicate",
    "CORE": "Center",
    "COST": "Price",
    "DARK": "Without light",
    "DATA": "Information",
    "DATE": "Calendar day",
    "DEAD": "Not alive",
    "DEAL": "Agreement",
    "DEAR": "Beloved",
    "DEEP": "Not shallow",
    "DESK": "Work table",
    "DOES": "Performs",
    "DONE": "Finished",
    "DOOR": "Entrance",
    "DOWN": "Lower",
    "DRAW": "Sketch",
    "DREW": "Sketched",
    "DROP": "Fall",
    "DRUG": "Medicine",
    "EACH": "Every one",
    "EAST": "Direction",
    "EASY": "Not hard",
    "EDGE": "Border",
    "ELSE": "Otherwise",
    "EVEN": "Level",
    "EVER": "At any time",
    "FACE": "Front of head",
    "FACT": "Truth",
    "FAIL": "Not succeed",
    "FAIR": "Just",
    "FALL": "Autumn",
    "FARM": "Agricultural land",
    "FAST": "Quick",
    "FEAR": "Fright",
    "FEED": "Give food",
    "FEEL": "Sense",
    "FEET": "Plural of foot",
    "FELL": "Dropped",
    "FILE": "Document",
    "FILL": "Make full",
    "FILM": "Movie",
    "FIND": "Discover",
    "FINE": "Good",
    "FIRE": "Flame",
    "FIRM": "Company",
    "FISH": "Aquatic animal",
    "FIVE": "Number",
    "FLAT": "Level",
    "FLEW": "Past tense of fly",
    "FLOW": "Stream",
    "FOOD": "Nourishment",
    "FOOT": "Body part",
    "FORM": "Shape",
    "FORT": "Military building",
    "FOUR": "Number",
    "FREE": "Without cost",
    "FROM": "Starting point",
    "FULL": "Filled",
    "FUND": "Money supply",
    "GAIN": "Acquire",
    "GAME": "Sport",
    "GAVE": "Past of give",
    "GIRL": "Young female",
    "GIVE": "Present",
    "GLAD": "Happy",
    "GOAL": "Objective",
    "GOES": "Moves",
    "GOLD": "Precious metal",
    "GONE": "Departed",
    "GOOD": "Positive",
    "GREW": "Increased",
    "GROW": "Increase",
    "HAIR": "Head covering",
    "HALF": "50 percent",
    "HALL": "Corridor",
    "HAND": "Body part",
    "HANG": "Suspend",
    "HARD": "Not soft",
    "HARM": "Damage",
    "HATE": "Strongly dislike",
    "HAVE": "Possess",
    "HEAD": "Top of body",
    "HEAR": "Listen",
    "HEAT": "Warmth",
    "HELD": "Grasped",
    "HELP": "Assist",
    "HERE": "This place",
    "HERO": "Brave person",
    "HIGH": "Tall",
    "HILL": "Small mountain",
    "HOLD": "Grasp",
    "HOLE": "Opening",
    "HOME": "Residence",
    "HOPE": "Wish",
    "HOST": "Party giver",
    "HOUR": "60 minutes",
    "HUGE": "Very large",
    "HUNG": "Suspended",
    "HUNT": "Search",
    "HURT": "Injure",
    "IDEA": "Thought",
    "INTO": "Inside",
    "IRON": "Metal",
    "ITEM": "Thing",
    "JACK": "Card face",
    "JAZZ": "Music genre",
    "JEAN": "Denim pants",
    "JOBS": "Work positions",
    "JOIN": "Connect",
    "JOKE": "Funny story",
    "JUMP": "Leap",
    "JUNE": "Month",
    "JURY": "Trial group",
    "JUST": "Fair",
    "KEEP": "Retain",
    "KEPT": "Retained",
    "KICK": "Foot strike",
    "KILL": "End life",
    "KIND": "Type",
    "KING": "Male monarch",
    "KNEE": "Leg joint",
    "KNEW": "Was aware",
    "KNOW": "Be aware",
    "LACK": "Be without",
    "LADY": "Woman",
    "LAID": "Put down",
    "LAKE": "Body of water",
    "LAND": "Earth",
    "LANE": "Narrow road",
    "LAST": "Final",
    "LATE": "Not on time",
    "LEAD": "Guide",
    "LEFT": "Opposite of right",
    "LESS": "Fewer",
    "LIFE": "Existence",
    "LIFT": "Raise",
    "LIKE": "Similar to",
    "LINE": "Row",
    "LINK": "Connection",
    "LIST": "Catalog",
    "LIVE": "Be alive",
    "LOAD": "Cargo",
    "LOAN": "Borrowed money",
    "LOCK": "Security device",
    "LOGO": "Brand symbol",
    "LONG": "Extended",
    "LOOK": "See",
    "LORD": "Nobleman",
    "LOSE": "Misplace",
    "LOSS": "Defeat",
    "LOST": "Misplaced",
    "LOTS": "Many",
    "LOVE": "Deep affection",
    "LUCK": "Fortune",
    "MADE": "Created",
    "MAIL": "Postal service",
    "MAIN": "Primary",
    "MAKE": "Create",
    "MALE": "Man",
    "MANY": "A lot",
    "MARK": "Sign",
    "MASS": "Large amount",
    "MEAL": "Food serving",
    "MEAN": "Intend",
    "MEET": "Encounter",
    "MENU": "Food list",
    "MILE": "Distance unit",
    "MILK": "Dairy drink",
    "MIND": "Brain",
    "MINE": "Belonging to me",
    "MISS": "Fail to hit",
    "MODE": "Method",
    "MOON": "Night light",
    "MORE": "Additional",
    "MOST": "Greatest amount",
    "MOVE": "Change position",
    "MUCH": "A lot",
    "MUST": "Have to",
    "NAME": "Title",
    "NEAR": "Close",
    "NECK": "Body part",
    "NEED": "Require",
    "NEWS": "Information",
    "NEXT": "Following",
    "NICE": "Pleasant",
    "NINE": "Number",
    "NONE": "Not any",
    "NOON": "Midday",
    "NOSE": "Face part",
    "NOTE": "Written message",
    "OKAY": "All right",
    "ONCE": "One time",
    "ONLY": "Sole",
    "ONTO": "Upon",
    "OPEN": "Not closed",
    "OVEN": "Baking appliance",
    "OVER": "Above",
    "PACE": "Speed",
    "PACK": "Bundle",
    "PAGE": "Paper sheet",
    "PAID": "Compensated",
    "PAIN": "Hurt",
    "PAIR": "Two",
    "PALM": "Hand center",
    "PARK": "Green area",
    "PART": "Piece",
    "PASS": "Go by",
    "PAST": "Before now",
    "PATH": "Trail",
    "PEAK": "Summit",
    "PICK": "Choose",
    "PLAN": "Strategy",
    "PLAY": "Game",
    "PLUS": "Addition",
    "POEM": "Verse",
    "POET": "Verse writer",
    "POLL": "Survey",
    "POOL": "Swimming area",
    "POOR": "Not rich",
    "POPE": "Catholic leader",
    "PORT": "Harbor",
    "POST": "Mail",
    "POUR": "Flow liquid",
    "PRAY": "Worship",
    "PULL": "Tug",
    "PURE": "Clean",
    "PUSH": "Shove",
    "QUIT": "Stop",
    "RACE": "Competition",
    "RAIN": "Precipitation",
    "RANK": "Position",
    "RARE": "Uncommon",
    "RATE": "Speed",
    "READ": "Look at text",
    "REAL": "True",
    "REAR": "Back",
    "RENT": "Lease payment",
    "REST": "Relax",
    "RICE": "Grain",
    "RICH": "Wealthy",
    "RIDE": "Travel",
    "RING": "Circle",
    "RISE": "Go up",
    "RISK": "Danger",
    "ROAD": "Street",
    "ROCK": "Stone",
    "ROLE": "Part",
    "ROLL": "Rotate",
    "ROOF": "House top",
    "ROOM": "Space",
    "ROOT": "Plant base",
    "ROSE": "Flower",
    "RULE": "Regulation",
    "RUNS": "Moves fast",
    "RUSH": "Hurry",
    "SAFE": "Secure",
    "SAID": "Spoke",
    "SAKE": "Purpose",
    "SALE": "Discount event",
    "SALT": "Seasoning",
    "SAME": "Identical",
    "SAND": "Beach material",
    "SAVE": "Rescue",
    "SEAT": "Chair",
    "SEEK": "Search for",
    "SEEM": "Appear",
    "SEEN": "Viewed",
    "SELF": "Oneself",
    "SELL": "Vend",
    "SEND": "Mail",
    "SENT": "Dispatched",
    "SHIP": "Water vessel",
    "SHOP": "Store",
    "SHOT": "Fired",
    "SHOW": "Display",
    "SHUT": "Close",
    "SICK": "Ill",
    "SIDE": "Edge",
    "SIGN": "Symbol",
    "SITE": "Location",
    "SIZE": "Dimension",
    "SKIN": "Body covering",
    "SLIP": "Slide",
    "SLOW": "Not fast",
    "SNOW": "Frozen precipitation",
    "SOFT": "Not hard",
    "SOIL": "Dirt",
    "SOLD": "Vended",
    "SOLE": "Only",
    "SOME": "A few",
    "SONG": "Musical piece",
    "SOON": "Shortly",
    "SORT": "Type",
    "SOUL": "Spirit",
    "SPOT": "Location",
    "STAR": "Celestial body",
    "STAY": "Remain",
    "STEP": "Pace",
    "STOP": "Cease",
    "SUCH": "Of that kind",
    "SUIT": "Business attire",
    "SURE": "Certain",
    "SWIM": "Water activity",
    "TAIL": "Rear appendage",
    "TAKE": "Grab",
    "TALE": "Story",
    "TALK": "Speak",
    "TALL": "High",
    "TANK": "Container",
    "TAPE": "Adhesive strip",
    "TASK": "Job",
    "TEAM": "Group",
    "TELL": "Inform",
    "TEND": "Care for",
    "TERM": "Word",
    "TEST": "Exam",
    "TEXT": "Written words",
    "THAN": "Comparison word",
    "THAT": "This thing",
    "THEM": "Those people",
    "THEN": "After that",
    "THEY": "Those people",
    "THIN": "Not thick",
    "THIS": "Current",
    "THUS": "Therefore",
    "TIDE": "Ocean movement",
    "TIED": "Fastened",
    "TILL": "Until",
    "TIME": "Duration",
    "TINY": "Very small",
    "TIPS": "Advice",
    "TIRE": "Wheel rubber",
    "TOLD": "Informed",
    "TONE": "Sound quality",
    "TOOK": "Grabbed",
    "TOOL": "Implement",
    "TOPS": "Best",
    "TOUR": "Trip",
    "TOWN": "Small city",
    "TREE": "Woody plant",
    "TRIP": "Journey",
    "TRUE": "Not false",
    "TUBE": "Cylinder",
    "TURN": "Rotate",
    "TYPE": "Kind",
    "UNIT": "Single item",
    "UPON": "On top of",
    "USED": "Utilized",
    "USER": "One who uses",
    "VARY": "Change",
    "VAST": "Huge",
    "VERB": "Action word",
    "VERY": "Extremely",
    "VIEW": "Sight",
    "VOTE": "Election choice",
    "WAGE": "Pay",
    "WAIT": "Stay",
    "WAKE": "Stop sleeping",
    "WALK": "Stroll",
    "WALL": "Room divider",
    "WANT": "Desire",
    "WARM": "Slightly hot",
    "WARN": "Alert",
    "WASH": "Clean",
    "WAVE": "Ocean motion",
    "WAYS": "Methods",
    "WEAK": "Not strong",
    "WEAR": "Put on",
    "WEEK": "Seven days",
    "WELL": "Good",
    "WENT": "Traveled",
    "WERE": "Past plural of be",
    "WEST": "Direction",
    "WHAT": "Which thing",
    "WHEN": "At what time",
    "WIDE": "Broad",
    "WIFE": "Married woman",
    "WILD": "Untamed",
    "WILL": "Going to",
    "WIND": "Air movement",
    "WINE": "Grape drink",
    "WING": "Bird part",
    "WIRE": "Metal strand",
    "WISE": "Smart",
    "WISH": "Desire",
    "WITH": "Alongside",
    "WOKE": "Awakened",
    "WOLF": "Wild canine",
    "WOOD": "Tree material",
    "WORD": "Vocabulary unit",
    "WORE": "Had on",
    "WORK": "Job",
    "WRAP": "Cover",
    "YARD": "Lawn",
    "YEAH": "Yes",
    "YEAR": "12 months",
    "YOUR": "Belonging to you",
    "ZERO": "Nothing",
    "ZONE": "Area",
    # Common 5-letter words
    "ABOUT": "Concerning",
    "ABOVE": "Higher than",
    "ABUSE": "Misuse",
    "ACTOR": "Performer",
    "ADMIT": "Confess",
    "ADOPT": "Take in",
    "ADULT": "Grown-up",
    "AFTER": "Following",
    "AGAIN": "Once more",
    "AGENT": "Representative",
    "AGREE": "Concur",
    "AHEAD": "In front",
    "ALARM": "Warning",
    "ALBUM": "Collection",
    "ALIEN": "Foreigner",
    "ALIKE": "Similar",
    "ALIVE": "Living",
    "ALLOW": "Permit",
    "ALONE": "By oneself",
    "ALONG": "Beside",
    "ALTER": "Change",
    "AMONG": "Amid",
    "ANGEL": "Heavenly being",
    "ANGER": "Rage",
    "ANGLE": "Corner",
    "ANGRY": "Mad",
    "APART": "Separate",
    "APPLE": "Fruit",
    "APPLY": "Request",
    "ARENA": "Stadium",
    "ARGUE": "Debate",
    "ARISE": "Get up",
    "ARMED": "With weapons",
    "ARMOR": "Protection",
    "ARRAY": "Collection",
    "ARROW": "Pointed missile",
    "ASIDE": "To the side",
    "ASSET": "Resource",
    "AVOID": "Stay away from",
    "AWARD": "Prize",
    "AWARE": "Conscious",
    "BADLY": "Poorly",
    "BASIC": "Fundamental",
    "BASIS": "Foundation",
    "BEACH": "Shore",
    "BEGAN": "Started",
    "BEGIN": "Start",
    "BEING": "Existing",
    "BELOW": "Under",
    "BENCH": "Seat",
    "BIBLE": "Holy book",
    "BLACK": "Dark color",
    "BLADE": "Sharp edge",
    "BLAME": "Fault",
    "BLANK": "Empty",
    "BLAST": "Explosion",
    "BLAZE": "Fire",
    "BLEND": "Mix",
    "BLESS": "Make holy",
    "BLIND": "Cannot see",
    "BLOCK": "Cube",
    "BLOOD": "Red fluid",
    "BLOOM": "Flower",
    "BLOWN": "Wind-affected",
    "BOARD": "Plank",
    "BOAST": "Brag",
    "BONUS": "Extra payment",
    "BOOST": "Increase",
    "BOOTH": "Small enclosure",
    "BOUND": "Limit",
    "BRAIN": "Thinking organ",
    "BRAND": "Product name",
    "BRAVE": "Courageous",
    "BREAD": "Baked food",
    "BREAK": "Shatter",
    "BREED": "Reproduce",
    "BRICK": "Building block",
    "BRIDE": "Woman marrying",
    "BRIEF": "Short",
    "BRING": "Carry",
    "BROAD": "Wide",
    "BROKE": "Shattered",
    "BROWN": "Earth color",
    "BRUSH": "Cleaning tool",
    "BUILD": "Construct",
    "BUILT": "Constructed",
    "BUNCH": "Group",
    "BURST": "Explode",
    "BUYER": "Purchaser",
    "CABLE": "Wire rope",
    "CALIF": "Islamic leader",
    "CANAL": "Water channel",
    "CANDY": "Sweet treat",
    "CARGO": "Freight",
    "CARRY": "Transport",
    "CARVE": "Cut shape",
    "CATCH": "Grab",
    "CAUSE": "Reason",
    "CEASE": "Stop",
    "CHAIN": "Linked metal",
    "CHAIR": "Seat",
    "CHAOS": "Disorder",
    "CHARM": "Appeal",
    "CHART": "Graph",
    "CHASE": "Pursue",
    "CHEAP": "Inexpensive",
    "CHEAT": "Deceive",
    "CHECK": "Verify",
    "CHEEK": "Face part",
    "CHEER": "Applause",
    "CHEST": "Body part",
    "CHIEF": "Leader",
    "CHILD": "Young person",
    "CHINA": "Country",
    "CHORD": "Musical notes",
    "CHOSE": "Selected",
    "CHUNK": "Large piece",
    "CLAIM": "Assert",
    "CLASS": "Category",
    "CLEAN": "Not dirty",
    "CLEAR": "Obvious",
    "CLERK": "Office worker",
    "CLICK": "Computer action",
    "CLIMB": "Ascend",
    "CLING": "Hold tight",
    "CLOCK": "Time device",
    "CLOSE": "Near",
    "CLOTH": "Fabric",
    "CLOUD": "Sky formation",
    "COACH": "Trainer",
    "COAST": "Shore",
    "COUCH": "Sofa",
    "COULD": "Was able",
    "COUNT": "Number",
    "COURT": "Legal place",
    "COVER": "Lid",
    "CRACK": "Split",
    "CRAFT": "Skill",
    "CRASH": "Collision",
    "CRAZY": "Insane",
    "CREAM": "Dairy product",
    "CREEK": "Stream",
    "CRIME": "Offense",
    "CRISP": "Crunchy",
    "CROSS": "Intersection",
    "CROWD": "Large group",
    "CROWN": "Royal headpiece",
    "CRUDE": "Raw",
    "CRUEL": "Mean",
    "CRUSH": "Squash",
    "CURVE": "Bend",
    "CYCLE": "Rotation",
    "DAILY": "Every day",
    "DAIRY": "Milk products",
    "DANCE": "Move to music",
    "DATED": "Old-fashioned",
    "DEALT": "Distributed",
    "DEATH": "End of life",
    "DEBUT": "First appearance",
    "DECAY": "Rot",
    "DELAY": "Postpone",
    "DENSE": "Thick",
    "DEPTH": "Deepness",
    "DEVIL": "Evil spirit",
    "DIARY": "Journal",
    "DIRTY": "Not clean",
    "DOUBT": "Uncertainty",
    "DOZEN": "Twelve",
    "DRAFT": "Rough version",
    "DRAIN": "Empty",
    "DRAMA": "Play",
    "DRANK": "Consumed liquid",
    "DRAWN": "Sketched",
    "DREAM": "Sleep vision",
    "DRESS": "Clothing",
    "DRIED": "Without moisture",
    "DRILL": "Tool",
    "DRINK": "Beverage",
    "DRIVE": "Operate vehicle",
    "DROIT": "Legal right",
    "DROVE": "Operated vehicle",
    "DROWN": "Suffocate in water",
    "DRUNK": "Intoxicated",
    "DWARF": "Small person",
    "DYING": "Near death",
    "EAGER": "Enthusiastic",
    "EARLY": "Before time",
    "EARTH": "Planet",
    "EATEN": "Consumed",
    "EIGHT": "Number",
    "ELDER": "Older person",
    "ELECT": "Choose",
    "ELITE": "Best",
    "EMERY": "Abrasive",
    "EMPTY": "Not full",
    "ENEMY": "Foe",
    "ENJOY": "Like",
    "ENTER": "Go in",
    "ENTRY": "Entrance",
    "EQUAL": "Same",
    "EQUIP": "Supply",
    "ERROR": "Mistake",
    "ESSAY": "Written work",
    "EVENT": "Occurrence",
    "EVERY": "Each",
    "EXACT": "Precise",
    "EXIST": "Be real",
    "EXTRA": "Additional",
    "FAINT": "Weak",
    "FAITH": "Belief",
    "FALSE": "Not true",
    "FAULT": "Defect",
    "FAVOR": "Support",
    "FEAST": "Big meal",
    "FENCE": "Barrier",
    "FEWER": "Less",
    "FIBER": "Thread",
    "FIELD": "Open land",
    "FIFTH": "Number",
    "FIFTY": "Number",
    "FIGHT": "Battle",
    "FINAL": "Last",
    "FIRST": "Before all",
    "FIXED": "Repaired",
    "FLAME": "Fire",
    "FLASH": "Quick light",
    "FLESH": "Body tissue",
    "FLOAT": "Stay on water",
    "FLOOD": "Water overflow",
    "FLOOR": "Room bottom",
    "FLOUR": "Baking powder",
    "FLUID": "Liquid",
    "FLUSH": "Rinse",
    "FOCUS": "Center",
    "FOGGY": "Misty",
    "FORCE": "Power",
    "FORGE": "Create",
    "FORTH": "Forward",
    "FORTY": "Number",
    "FORUM": "Discussion place",
    "FOUND": "Discovered",
    "FRAME": "Border",
    "FRANK": "Honest",
    "FRAUD": "Deception",
    "FRESH": "New",
    "FRONT": "Forward side",
    "FROST": "Frozen dew",
    "FRUIT": "Plant product",
    "FULLY": "Completely",
    "FUNNY": "Humorous",
    "GIANT": "Very large",
    "GIVEN": "Presented",
    "GLASS": "Transparent material",
    "GLOBE": "Sphere",
    "GLORY": "Fame",
    "GOING": "Moving",
    "GRACE": "Elegance",
    "GRADE": "Level",
    "GRAIN": "Cereal",
    "GRAND": "Great",
    "GRANT": "Give",
    "GRAPE": "Fruit",
    "GRASP": "Hold",
    "GRASS": "Lawn plant",
    "GRAVE": "Burial place",
    "GREAT": "Excellent",
    "GREEN": "Color",
    "GREET": "Welcome",
    "GRIEF": "Sadness",
    "GRILL": "Cooking device",
    "GRIND": "Crush",
    "GROSS": "Total",
    "GROUP": "Collection",
    "GROVE": "Small forest",
    "GROWN": "Matured",
    "GUARD": "Protector",
    "GUESS": "Estimate",
    "GUEST": "Visitor",
    "GUIDE": "Leader",
    "GUILT": "Fault",
    "HABIT": "Routine",
    "HANDS": "Body parts",
    "HANDY": "Useful",
    "HAPPY": "Joyful",
    "HARSH": "Severe",
    "HASN'T": "Has not",
    "HASTE": "Hurry",
    "HAVEN": "Safe place",
    "HEART": "Organ",
    "HEAVY": "Weighty",
    "HELLO": "Greeting",
    "HENCE": "Therefore",
    "HERBS": "Plants",
    "HIRED": "Employed",
    "HOBBY": "Pastime",
    "HONEY": "Sweet liquid",
    "HONOR": "Respect",
    "HORSE": "Animal",
    "HOTEL": "Lodging",
    "HOUND": "Dog type",
    "HOUSE": "Home",
    "HUMAN": "Person",
    "HUMOR": "Comedy",
    "HURRY": "Rush",
    "IDEAL": "Perfect",
    "IMAGE": "Picture",
    "IMPLY": "Suggest",
    "INDEX": "List",
    "INDIA": "Country",
    "INNER": "Inside",
    "INPUT": "Data entry",
    "IRONY": "Sarcasm",
    "ISSUE": "Problem",
    "ITEMS": "Things",
    "JAPAN": "Country",
    "JEANS": "Pants",
    "JOINT": "Connection",
    "JONES": "Common name",
    "JUDGE": "Arbiter",
    "JUICE": "Drink",
    "KEEPS": "Retains",
    "KNIFE": "Cutting tool",
    "KNOCK": "Hit",
    "KNOWN": "Familiar",
    "LABEL": "Tag",
    "LABOR": "Work",
    "LARGE": "Big",
    "LASER": "Light beam",
    "LATER": "After",
    "LATIN": "Language",
    "LAUGH": "Chuckle",
    "LAYER": "Level",
    "LEARN": "Study",
    "LEASE": "Rental",
    "LEAST": "Minimum",
    "LEAVE": "Depart",
    "LEGAL": "Lawful",
    "LEMON": "Citrus fruit",
    "LEVEL": "Flat",
    "LEVER": "Simple machine",
    "LIGHT": "Illumination",
    "LIKED": "Enjoyed",
    "LIMIT": "Boundary",
    "LINKS": "Connections",
    "LIONS": "Big cats",
    "LISTS": "Catalogs",
    "LIVED": "Resided",
    "LIVER": "Organ",
    "LIVES": "Exists",
    "LOCAL": "Nearby",
    "LODGE": "Cabin",
    "LOGIC": "Reasoning",
    "LOOSE": "Not tight",
    "LORDS": "Nobles",
    "LOVER": "Partner",
    "LOWER": "Reduce",
    "LOYAL": "Faithful",
    "LUCKY": "Fortunate",
    "LUNCH": "Midday meal",
    "LYING": "Not truthful",
    "MAGIC": "Illusion",
    "MAJOR": "Significant",
    "MAKER": "Creator",
    "MANOR": "Estate",
    "MARCH": "Walk",
    "MARRY": "Wed",
    "MATCH": "Contest",
    "MAYOR": "City leader",
    "MEANS": "Methods",
    "MEANT": "Intended",
    "MEDAL": "Award",
    "MEDIA": "News outlets",
    "MELON": "Fruit",
    "MERCY": "Forgiveness",
    "MERGE": "Combine",
    "MERIT": "Worth",
    "MERRY": "Joyful",
    "METAL": "Material",
    "METER": "Unit",
    "MIDST": "Middle",
    "MIGHT": "Power",
    "MINER": "Digger",
    "MINOR": "Small",
    "MINUS": "Less",
    "MIXED": "Combined",
    "MODEL": "Example",
    "MOIST": "Slightly wet",
    "MONEY": "Currency",
    "MONTH": "Time period",
    "MORAL": "Ethical",
    "MOTOR": "Engine",
    "MOUNT": "Climb",
    "MOUSE": "Small rodent",
    "MOUTH": "Face opening",
    "MOVED": "Changed position",
    "MOVIE": "Film",
    "MUSIC": "Melodies",
    "NAKED": "Unclothed",
    "NAMED": "Called",
    "NAMES": "Titles",
    "NAVAL": "Navy-related",
    "NEEDS": "Requires",
    "NERVE": "Body part",
    "NEVER": "Not ever",
    "NEWLY": "Recently",
    "NIGHT": "Dark time",
    "NINTH": "Number",
    "NOISE": "Sound",
    "NORTH": "Direction",
    "NOTED": "Famous",
    "NOTES": "Written records",
    "NOVEL": "Book",
    "NURSE": "Medical worker",
    "OCCUR": "Happen",
    "OCEAN": "Large water body",
    "OFFER": "Present",
    "OFTEN": "Frequently",
    "OLDER": "More aged",
    "OLIVE": "Green fruit",
    "ONION": "Vegetable",
    "OPENS": "Unlocks",
    "OPERA": "Musical drama",
    "ORBIT": "Path",
    "ORDER": "Arrangement",
    "ORGAN": "Body part",
    "OTHER": "Different",
    "OUGHT": "Should",
    "OUTER": "External",
    "OWNED": "Possessed",
    "OWNER": "Possessor",
    "OXIDE": "Chemical compound",
    "PAINT": "Color coating",
    "PAIRS": "Twos",
    "PANEL": "Board",
    "PANIC": "Fear",
    "PAPER": "Writing material",
    "PARTY": "Celebration",
    "PASTA": "Italian food",
    "PATCH": "Small piece",
    "PAUSE": "Stop briefly",
    "PEACE": "Calm",
    "PEARL": "Gem",
    "PENNY": "Coin",
    "PHASE": "Stage",
    "PHONE": "Telephone",
    "PHOTO": "Picture",
    "PIANO": "Instrument",
    "PIECE": "Part",
    "PILOT": "Flyer",
    "PITCH": "Throw",
    "PIXEL": "Screen dot",
    "PLACE": "Location",
    "PLAIN": "Simple",
    "PLANE": "Aircraft",
    "PLANT": "Flora",
    "PLATE": "Dish",
    "PLAZA": "Square",
    "PLEAD": "Beg",
    "PLAZA": "Public square",
    "POINT": "Tip",
    "POLAR": "Arctic",
    "POLLS": "Surveys",
    "POUCH": "Bag",
    "POUND": "Weight unit",
    "POWER": "Strength",
    "PRESS": "Push",
    "PRICE": "Cost",
    "PRIDE": "Self-respect",
    "PRIME": "First",
    "PRINT": "Text",
    "PRIOR": "Before",
    "PRIZE": "Award",
    "PROBE": "Investigate",
    "PROOF": "Evidence",
    "PROUD": "Self-satisfied",
    "PROVE": "Demonstrate",
    "PUPIL": "Student",
    "QUEEN": "Female monarch",
    "QUEST": "Search",
    "QUICK": "Fast",
    "QUIET": "Silent",
    "QUITE": "Very",
    "QUOTE": "Citation",
    "RADAR": "Detection system",
    "RADIO": "Broadcast",
    "RAISE": "Lift",
    "RANCH": "Farm",
    "RANGE": "Scope",
    "RAPID": "Fast",
    "RATIO": "Proportion",
    "REACH": "Extend to",
    "REACT": "Respond",
    "READS": "Looks at text",
    "READY": "Prepared",
    "REALM": "Kingdom",
    "REBEL": "Resist",
    "REFER": "Direct",
    "REIGN": "Rule",
    "RELAX": "Rest",
    "RELAY": "Pass on",
    "REPLY": "Respond",
    "RIDER": "One who rides",
    "RIDGE": "Mountain top",
    "RIFLE": "Gun",
    "RIGHT": "Correct",
    "RIGID": "Stiff",
    "RISKY": "Dangerous",
    "RIVAL": "Competitor",
    "RIVER": "Water body",
    "ROAST": "Cook",
    "ROBOT": "Machine",
    "ROGER": "Name",
    "ROMAN": "Of Rome",
    "ROOTS": "Plant bases",
    "ROUGH": "Not smooth",
    "ROUND": "Circular",
    "ROUTE": "Path",
    "ROYAL": "Regal",
    "RUGBY": "Sport",
    "RULED": "Governed",
    "RULER": "Leader",
    "RULES": "Regulations",
    "RURAL": "Countryside",
    "SADLY": "Unfortunately",
    "SAINT": "Holy person",
    "SALAD": "Vegetable dish",
    "SALES": "Selling",
    "SANDY": "With sand",
    "SANTA": "Christmas figure",
    "SAUCE": "Condiment",
    "SAVED": "Rescued",
    "SCALE": "Measurement",
    "SCARY": "Frightening",
    "SCENE": "Setting",
    "SCENT": "Smell",
    "SCOPE": "Range",
    "SCORE": "Points",
    "SCOUT": "Explorer",
    "SCREW": "Fastener",
    "SEIZE": "Grab",
    "SENSE": "Feeling",
    "SERVE": "Help",
    "SETUP": "Arrangement",
    "SEVEN": "Number",
    "SHADE": "Shadow",
    "SHAFT": "Pole",
    "SHAKE": "Tremble",
    "SHALL": "Will",
    "SHAME": "Disgrace",
    "SHAPE": "Form",
    "SHARE": "Divide",
    "SHARK": "Fish",
    "SHARP": "Pointed",
    "SHEEP": "Farm animal",
    "SHEER": "Pure",
    "SHEET": "Flat material",
    "SHELF": "Storage",
    "SHELL": "Hard covering",
    "SHIFT": "Change",
    "SHINE": "Glow",
    "SHIRT": "Clothing",
    "SHOCK": "Surprise",
    "SHOES": "Footwear",
    "SHOOK": "Trembled",
    "SHOOT": "Fire",
    "SHORE": "Beach",
    "SHORT": "Not tall",
    "SHOUT": "Yell",
    "SHOWN": "Displayed",
    "SIDED": "Took sides",
    "SIGHT": "Vision",
    "SIGNS": "Symbols",
    "SILLY": "Foolish",
    "SINCE": "Because",
    "SIXTH": "Number",
    "SIXTY": "Number",
    "SIZED": "Measured",
    "SIZES": "Dimensions",
    "SKILL": "Ability",
    "SKULL": "Head bone",
    "SLASH": "Cut",
    "SLATE": "Rock",
    "SLAVE": "Captive",
    "SLEEP": "Rest",
    "SLICE": "Piece",
    "SLIDE": "Glide",
    "SLOPE": "Incline",
    "SMALL": "Little",
    "SMART": "Intelligent",
    "SMELL": "Odor",
    "SMILE": "Grin",
    "SMITH": "Metalworker",
    "SMOKE": "Vapor",
    "SNAKE": "Reptile",
    "SOLAR": "Sun-related",
    "SOLID": "Firm",
    "SOLVE": "Figure out",
    "SORRY": "Apologetic",
    "SORTS": "Types",
    "SOULS": "Spirits",
    "SOUND": "Noise",
    "SOUTH": "Direction",
    "SPACE": "Area",
    "SPARE": "Extra",
    "SPARK": "Flash",
    "SPEAK": "Talk",
    "SPEED": "Velocity",
    "SPELL": "Magic words",
    "SPEND": "Use money",
    "SPENT": "Used money",
    "SPICE": "Flavoring",
    "SPILL": "Overflow",
    "SPINE": "Backbone",
    "SPLIT": "Divide",
    "SPOKE": "Said",
    "SPORT": "Game",
    "SPOTS": "Locations",
    "SPRAY": "Mist",
    "SQUAD": "Team",
    "STACK": "Pile",
    "STAFF": "Workers",
    "STAGE": "Platform",
    "STAIN": "Mark",
    "STAIR": "Step",
    "STAKE": "Bet",
    "STAMP": "Mark",
    "STAND": "Be upright",
    "STARK": "Bare",
    "START": "Begin",
    "STATE": "Condition",
    "STAYS": "Remains",
    "STEAM": "Water vapor",
    "STEEL": "Metal",
    "STEEP": "Sharply inclined",
    "STEER": "Guide",
    "STEMS": "Plant parts",
    "STEPS": "Stairs",
    "STERN": "Strict",
    "STICK": "Thin branch",
    "STIFF": "Rigid",
    "STILL": "Not moving",
    "STOCK": "Supply",
    "STOLE": "Took wrongly",
    "STONE": "Rock",
    "STOOD": "Was upright",
    "STOOL": "Seat",
    "STOPS": "Halts",
    "STORE": "Shop",
    "STORM": "Bad weather",
    "STORY": "Tale",
    "STOVE": "Cooking device",
    "STRAP": "Band",
    "STRAW": "Dried grass",
    "STRIP": "Remove",
    "STUCK": "Attached",
    "STUDY": "Learn",
    "STUFF": "Things",
    "STYLE": "Fashion",
    "SUGAR": "Sweetener",
    "SUITE": "Room set",
    "SUNNY": "Bright",
    "SUPER": "Great",
    "SURGE": "Rush",
    "SWAMP": "Wetland",
    "SWEAR": "Promise",
    "SWEAT": "Perspiration",
    "SWEET": "Sugary",
    "SWEPT": "Cleaned",
    "SWIFT": "Fast",
    "SWING": "Move back and forth",
    "SWORD": "Weapon",
    "SWORE": "Promised",
    "SWORN": "Vowed",
    "TABLE": "Furniture",
    "TAKEN": "Grabbed",
    "TAKES": "Grabs",
    "TALKS": "Speaks",
    "TASTE": "Flavor",
    "TAXES": "Government fees",
    "TEACH": "Instruct",
    "TEAMS": "Groups",
    "TEARS": "Eye drops",
    "TEETH": "Mouth bones",
    "TELLS": "Informs",
    "TEMPO": "Speed",
    "TENDS": "Cares for",
    "TERMS": "Conditions",
    "TESTS": "Exams",
    "TEXAS": "State",
    "THANK": "Express gratitude",
    "THEFT": "Stealing",
    "THEIR": "Belonging to them",
    "THEME": "Topic",
    "THERE": "That place",
    "THESE": "These things",
    "THICK": "Not thin",
    "THIEF": "Robber",
    "THING": "Object",
    "THINK": "Ponder",
    "THIRD": "After second",
    "THOSE": "Those things",
    "THREE": "Number",
    "THREW": "Tossed",
    "THROW": "Toss",
    "THUMB": "Finger",
    "TIGER": "Big cat",
    "TIGHT": "Snug",
    "TIRED": "Exhausted",
    "TITLE": "Name",
    "TODAY": "This day",
    "TOKEN": "Symbol",
    "TOLLS": "Fees",
    "TONES": "Sounds",
    "TOPIC": "Subject",
    "TORCH": "Light",
    "TOTAL": "Sum",
    "TOUCH": "Feel",
    "TOUGH": "Hard",
    "TOWER": "Tall building",
    "TOWNS": "Small cities",
    "TOXIC": "Poisonous",
    "TRACE": "Track",
    "TRACK": "Path",
    "TRADE": "Exchange",
    "TRAIL": "Path",
    "TRAIN": "Railway vehicle",
    "TRAIT": "Characteristic",
    "TRASH": "Garbage",
    "TREAT": "Gift",
    "TREES": "Plants",
    "TREND": "Fashion",
    "TRIAL": "Test",
    "TRIBE": "Group",
    "TRICK": "Prank",
    "TRIED": "Attempted",
    "TRIES": "Attempts",
    "TRIPS": "Journeys",
    "TROOP": "Group",
    "TRUCK": "Vehicle",
    "TRULY": "Really",
    "TRUMP": "Beat",
    "TRUNK": "Tree part",
    "TRUST": "Faith",
    "TRUTH": "Fact",
    "TUBES": "Cylinders",
    "TURNS": "Rotates",
    "TWICE": "Two times",
    "TWINS": "Two siblings",
    "TWIST": "Turn",
    "TYPED": "Keyed in",
    "TYPES": "Kinds",
    "UNCLE": "Relative",
    "UNDER": "Below",
    "UNION": "Organization",
    "UNITE": "Join",
    "UNITS": "Items",
    "UNITY": "Togetherness",
    "UNTIL": "Up to",
    "UPPER": "Higher",
    "UPSET": "Disturbed",
    "URBAN": "City-related",
    "URGES": "Encourages",
    "USAGE": "Use",
    "USUAL": "Normal",
    "VALID": "Legal",
    "VALUE": "Worth",
    "VALVE": "Flow control",
    "VAPOR": "Gas",
    "VAULT": "Safe",
    "VENUE": "Location",
    "VERSE": "Poetry",
    "VIDEO": "Recording",
    "VIEWS": "Opinions",
    "VILLA": "House",
    "VIRUS": "Germ",
    "VISIT": "Go see",
    "VITAL": "Essential",
    "VIVID": "Bright",
    "VOCAL": "Voice-related",
    "VOICE": "Sound",
    "VOTER": "One who votes",
    "VOTES": "Ballots",
    "WAGES": "Pay",
    "WAGON": "Cart",
    "WAIST": "Body part",
    "WALKS": "Strolls",
    "WALLS": "Barriers",
    "WANTS": "Desires",
    "WASTE": "Trash",
    "WATCH": "Timepiece",
    "WATER": "H2O",
    "WAVES": "Ocean motions",
    "WEEKS": "Time periods",
    "WEIGH": "Measure weight",
    "WEIRD": "Strange",
    "WELLS": "Water sources",
    "WHALE": "Large mammal",
    "WHEAT": "Grain",
    "WHEEL": "Circular object",
    "WHERE": "What place",
    "WHICH": "What one",
    "WHILE": "During",
    "WHITE": "Color",
    "WHOLE": "Complete",
    "WHOSE": "Belonging to whom",
    "WIDER": "More broad",
    "WIDTH": "Breadth",
    "WINES": "Drinks",
    "WINGS": "Flying parts",
    "WIRES": "Metal strands",
    "WITCH": "Sorceress",
    "WIVES": "Married women",
    "WOKEN": "Awakened",
    "WOMAN": "Adult female",
    "WOMEN": "Adult females",
    "WOODS": "Forest",
    "WORDS": "Vocabulary",
    "WORKS": "Functions",
    "WORLD": "Earth",
    "WORRY": "Fret",
    "WORSE": "More bad",
    "WORST": "Most bad",
    "WORTH": "Value",
    "WOULD": "Conditional",
    "WOUND": "Injury",
    "WRAP": "Cover",
    "WRIST": "Body part",
    "WRITE": "Put pen to paper",
    "WRONG": "Incorrect",
    "WROTE": "Authored",
    "YARDS": "Lawns",
    "YEARS": "Time periods",
    "YIELD": "Produce",
    "YOUNG": "Not old",
    "YOURS": "Belonging to you",
    "YOUTH": "Young person",
    "ZONES": "Areas",
}


def get_clue_for_word(word: str) -> str:
    """Get a clue for a word, using templates or generating a simple one."""
    word_upper = word.upper()
    if word_upper in CLUE_TEMPLATES:
        return CLUE_TEMPLATES[word_upper]
    # Default clue
    return f"{len(word)}-letter word"


# Additional common crossword words not in the clue templates
# These are verified common English words good for crosswords
EXTRA_COMMON_WORDS = {
    # 3-letter words (common crossword fill)
    "ACE", "ACT", "ADD", "AGE", "AID", "AIM", "AIR", "ALE", "ALL", "AND", "ANT", "ANY", "APE", "ARC", "ARE", "ARK", "ARM", "ART", "ASH", "ATE",
    "AWE", "AXE", "BAD", "BAG", "BAN", "BAR", "BAT", "BAY", "BED", "BEE", "BET", "BIG", "BIT", "BOW", "BOX", "BOY", "BUD", "BUG", "BUS", "BUT",
    "BUY", "CAB", "CAN", "CAP", "CAR", "CAT", "COB", "COD", "COG", "COP", "COT", "COW", "CRY", "CUB", "CUD", "CUP", "CUR", "CUT", "DAB", "DAD",
    "DAM", "DAY", "DEN", "DEW", "DID", "DIE", "DIG", "DIM", "DIP", "DOC", "DOE", "DOG", "DOT", "DRY", "DUB", "DUD", "DUE", "DUG", "DYE", "EAR",
    "EAT", "EEL", "EGG", "ELF", "ELK", "ELM", "EMU", "END", "ERA", "ERR", "EVE", "EWE", "EYE", "FAN", "FAR", "FAT", "FAX", "FED", "FEE", "FEW",
    "FIG", "FIN", "FIR", "FIT", "FIX", "FLU", "FLY", "FOB", "FOE", "FOG", "FOR", "FOX", "FRY", "FUN", "FUR", "GAB", "GAG", "GAL", "GAP", "GAS",
    "GEL", "GEM", "GET", "GIG", "GIN", "GNU", "GOB", "GOD", "GOT", "GUM", "GUN", "GUT", "GUY", "GYM", "HAD", "HAM", "HAS", "HAT", "HAY", "HEM",
    "HEN", "HER", "HEW", "HID", "HIM", "HIP", "HIS", "HIT", "HOB", "HOD", "HOG", "HOP", "HOT", "HOW", "HUB", "HUE", "HUG", "HUM", "HUT", "ICE",
    "ICY", "ILL", "IMP", "INK", "INN", "ION", "IRE", "IRK", "ITS", "IVY", "JAB", "JAG", "JAM", "JAR", "JAW", "JAY", "JET", "JIG", "JOB", "JOG",
    "JOT", "JOY", "JUG", "JUT", "KEG", "KEN", "KEY", "KID", "KIN", "KIT", "LAB", "LAC", "LAD", "LAG", "LAP", "LAW", "LAX", "LAY", "LEA", "LED",
    "LEG", "LET", "LID", "LIE", "LIP", "LIT", "LOG", "LOT", "LOW", "LUG", "MAD", "MAN", "MAP", "MAR", "MAT", "MAW", "MAY", "MEN", "MET", "MID",
    "MIX", "MOB", "MOM", "MOP", "MOW", "MUD", "MUG", "MUM", "NAB", "NAG", "NAP", "NET", "NEW", "NIL", "NIP", "NIT", "NOB", "NOD", "NOR", "NOT",
    "NOW", "NUB", "NUN", "NUT", "OAK", "OAR", "OAT", "ODD", "ODE", "OFF", "OFT", "OHM", "OIL", "OLD", "ONE", "OPT", "ORB", "ORE", "OUR", "OUT",
    "OWE", "OWL", "OWN", "PAD", "PAL", "PAN", "PAR", "PAT", "PAW", "PAY", "PEA", "PEG", "PEN", "PEP", "PER", "PET", "PEW", "PIE", "PIG", "PIN",
    "PIT", "PLY", "POD", "POP", "POT", "POW", "PRY", "PUB", "PUG", "PUN", "PUP", "PUS", "PUT", "RAG", "RAM", "RAN", "RAP", "RAT", "RAW", "RAY",
    "RED", "REF", "REP", "RIB", "RID", "RIG", "RIM", "RIP", "ROB", "ROD", "ROE", "ROT", "ROW", "RUB", "RUG", "RUM", "RUN", "RUT", "RYE", "SAC",
    "SAD", "SAG", "SAP", "SAT", "SAW", "SAY", "SEA", "SET", "SEW", "SHE", "SHY", "SIN", "SIP", "SIR", "SIS", "SIT", "SIX", "SKI", "SKY", "SLY",
    "SOB", "SOD", "SON", "SOP", "SOT", "SOW", "SOY", "SPA", "SPY", "STY", "SUB", "SUM", "SUN", "SUP", "TAB", "TAD", "TAG", "TAN", "TAP", "TAR",
    "TAT", "TAX", "TEA", "TEN", "THE", "THY", "TIC", "TIE", "TIN", "TIP", "TOE", "TON", "TOO", "TOP", "TOT", "TOW", "TOY", "TRY", "TUB", "TUG",
    "TWO", "URN", "USE", "VAN", "VAT", "VET", "VIA", "VIE", "VOW", "WAD", "WAG", "WAR", "WAS", "WAX", "WAY", "WEB", "WED", "WEE", "WET", "WHO",
    "WHY", "WIG", "WIN", "WIT", "WOE", "WOK", "WON", "WOO", "WOW", "YAK", "YAM", "YAP", "YAW", "YEA", "YES", "YET", "YEW", "YIN", "YOU", "ZAP",
    "ZEN", "ZIP", "ZIT", "ZOO",
    # 4-letter words
    "ABLE", "ACHE", "ACID", "ACRE", "AGED", "AIDE", "AJAR", "AKIN", "ALLY", "ALSO", "AMID", "ANKL", "ANTE", "ARCH", "AREA", "ARIA", "ARMY",
    "ARTS", "AUNT", "AUTO", "AVID", "AXIS", "BABE", "BABY", "BACK", "BADE", "BAIL", "BAIT", "BAKE", "BALD", "BALE", "BALL", "BALM", "BAND",
    "BANE", "BANK", "BARE", "BARK", "BARN", "BASE", "BATH", "BAWL", "BEAD", "BEAK", "BEAM", "BEAN", "BEAR", "BEAT", "BECK", "BEEN", "BEEF",
    "BEER", "BELL", "BELT", "BEND", "BENT", "BERG", "BEST", "BIAS", "BIDE", "BIKE", "BILE", "BILL", "BIND", "BIRD", "BITE", "BLAH", "BLED",
    "BLEW", "BLOB", "BLOC", "BLOG", "BLOW", "BLUE", "BLUR", "BOAR", "BOAT", "BODY", "BOIL", "BOLD", "BOLT", "BOMB", "BOND", "BONE", "BOOK",
    "BOOM", "BOON", "BOOT", "BORE", "BORN", "BOSS", "BOTH", "BOUT", "BOWL", "BRAG", "BRAN", "BRAT", "BRED", "BREW", "BRIM", "BRIT", "BROW",
    "BUCK", "BUFF", "BULB", "BULK", "BULL", "BUMP", "BUNK", "BURN", "BURP", "BURY", "BUSH", "BUST", "BUSY", "CAFE", "CAGE", "CAKE", "CALF",
    "CALL", "CALM", "CAME", "CAMP", "CANE", "CAPE", "CARD", "CARE", "CARP", "CART", "CASE", "CASH", "CASK", "CAST", "CAVE", "CELL", "CHAP",
    "CHAR", "CHAT", "CHEF", "CHEW", "CHIC", "CHIN", "CHIP", "CHOP", "CHOW", "CITE", "CITY", "CLAD", "CLAM", "CLAN", "CLAP", "CLAW", "CLAY",
    "CLIP", "CLOD", "CLOG", "CLOT", "CLUB", "CLUE", "COAL", "COAT", "CODE", "COIL", "COIN", "COLD", "COLE", "COLT", "COMB", "COME", "CONE",
    "COOK", "COOL", "COPE", "COPY", "CORD", "CORE", "CORK", "CORN", "COST", "COSY", "COUP", "COVE", "COZY", "CRAB", "CRAM", "CRAP", "CREW",
    "CRIB", "CROP", "CROW", "CUBE", "CUFF", "CULT", "CURB", "CURE", "CURL", "CUTE", "DAFT", "DAME", "DAMP", "DANK", "DARE", "DARK", "DARN",
    "DART", "DASH", "DATA", "DATE", "DAWN", "DAYS", "DAZE", "DEAD", "DEAF", "DEAL", "DEAN", "DEAR", "DEBT", "DECK", "DEED", "DEEM", "DEEP",
    "DEER", "DEMO", "DENT", "DENY", "DESK", "DIAL", "DICE", "DIED", "DIET", "DIME", "DINE", "DING", "DIRE", "DIRT", "DISC", "DISH", "DISK",
    "DIVE", "DOCK", "DODO", "DOER", "DOES", "DOLE", "DOLL", "DOME", "DONE", "DOOM", "DOOR", "DOPE", "DORK", "DOSE", "DOTE", "DOTH", "DOZE",
    "DRAG", "DRAM", "DRAW", "DREW", "DRIP", "DROP", "DRUG", "DRUM", "DUAL", "DRAB", "DUCE", "DUCK", "DUCT", "DUDE", "DUEL", "DUET", "DUKE",
    "DULL", "DULY", "DUMB", "DUMP", "DUNE", "DUNG", "DUNK", "DUPE", "DUSK", "DUST", "DUTY", "DYED", "EACH", "EARL", "EARN", "EASE", "EAST",
    "EASY", "EATS", "EAVE", "ECHO", "EDGE", "EDGY", "EDIT", "EELS", "EGAD", "EGGS", "ELSE", "EMIT", "ENDS", "ENVY", "EPIC", "ETCH", "EURO",
    "EVEN", "EVER", "EVIL", "EXAM", "EXIT", "EXPO", "FACE", "FACT", "FADE", "FAIL", "FAIR", "FAKE", "FALL", "FAME", "FANG", "FARE", "FARM",
    "FAST", "FATE", "FAWN", "FEAR", "FEAT", "FEED", "FEEL", "FEES", "FEET", "FELL", "FELT", "FEND", "FERN", "FEST", "FEUD", "FILE", "FILL",
    "FILM", "FIND", "FINE", "FIRE", "FIRM", "FISH", "FIST", "FIVE", "FLAG", "FLAK", "FLAM", "FLAN", "FLAP", "FLAT", "FLAW", "FLAX", "FLEA",
    "FLED", "FLEE", "FLEW", "FLEX", "FLIP", "FLIT", "FLOG", "FLOP", "FLOW", "FLUB", "FLUE", "FLUX", "FOAM", "FOES", "FOIL", "FOLD", "FOLK",
    "FOND", "FONT", "FOOD", "FOOL", "FOOT", "FORD", "FORE", "FORK", "FORM", "FORT", "FOUL", "FOUR", "FOWL", "FRAY", "FREE", "FRET", "FROG",
    "FROM", "FUEL", "FULL", "FUME", "FUND", "FUNK", "FURL", "FURY", "FUSE", "FUSS", "FUZZ", "GAGA", "GAGE", "GAIN", "GAIT", "GALA", "GALE",
    "GALL", "GAME", "GANG", "GAPE", "GARB", "GASH", "GASP", "GATE", "GAVE", "GAWK", "GAZE", "GEAR", "GEEK", "GENE", "GENT", "GERM", "GETS",
    "GIFT", "GILD", "GILL", "GILT", "GIRD", "GIRL", "GIST", "GIVE", "GLAD", "GLAM", "GLEE", "GLEN", "GLIB", "GLIM", "GLOB", "GLOM", "GLOP",
    "GLOW", "GLUE", "GLUM", "GLUT", "GNAR", "GNAW", "GOAD", "GOAL", "GOAT", "GOES", "GOLD", "GOLF", "GONE", "GONG", "GOOD", "GOOF", "GORE",
    "GORY", "GOSH", "GOUT", "GOWN", "GRAB", "GRAM", "GRAN", "GRAY", "GREW", "GREY", "GRID", "GRIM", "GRIN", "GRIP", "GRIT", "GROG", "GROOM",
    "GROW", "GRUB", "GULP", "GUNK", "GUST", "GUTS", "GUYS", "GYMS", "HACK", "HAIL", "HAIR", "HALE", "HALF", "HALL", "HALO", "HALT", "HAND",
    "HANG", "HANK", "HARE", "HARK", "HARM", "HARP", "HASH", "HASP", "HATE", "HATH", "HAUL", "HAVE", "HAWK", "HAZE", "HAZY", "HEAD", "HEAL",
    "HEAP", "HEAR", "HEAT", "HECK", "HEED", "HEEL", "HEFT", "HEIR", "HELD", "HELL", "HELM", "HELP", "HEMP", "HENS", "HERB", "HERD", "HERE",
    "HERO", "HERS", "HEWN", "HICK", "HIDE", "HIGH", "HIKE", "HILL", "HILT", "HIND", "HINT", "HIRE", "HISS", "HITS", "HIVE", "HOAX", "HOBS",
    "HOCK", "HOED", "HOGS", "HOLD", "HOLE", "HOLY", "HOME", "HONE", "HONK", "HOOD", "HOOF", "HOOK", "HOOP", "HOOT", "HOPE", "HOPS", "HORN",
    "HOSE", "HOST", "HOUR", "HOWL", "HUBS", "HUED", "HUES", "HUFF", "HUGE", "HUGS", "HULK", "HULL", "HUMP", "HUMS", "HUNG", "HUNK", "HUNT",
    "HURL", "HURT", "HUSH", "HUSK", "HYMN", "HYPE", "IBIS", "ICED", "ICES", "ICON", "IDEA", "IDLE", "IDLY", "IDOL", "IFFY", "ILLS", "IMAM",
    "IMPS", "INCH", "INFO", "INKS", "INNS", "INTO", "IONS", "IOTA", "IRIS", "IRKS", "IRON", "ISLE", "ITCH", "ITEM", "JABS", "JACK", "JADE",
    "JAGS", "JAIL", "JAMB", "JAMS", "JANE", "JARS", "JAVA", "JAWS", "JAYS", "JAZZ", "JEAN", "JEER", "JELL", "JERK", "JEST", "JETS", "JIBE",
    "JIGS", "JILT", "JINX", "JIVE", "JOBS", "JOCK", "JOGS", "JOIN", "JOKE", "JOLT", "JOSH", "JOTS", "JOWL", "JOYS", "JUDO", "JUGS", "JUMP",
    "JUNE", "JUNK", "JURY", "JUST", "JUTS", "KALE", "KEEN", "KEEP", "KEGS", "KELP", "KEPT", "KERN", "KEYS", "KICK", "KIDS", "KILL", "KILN",
    "KILT", "KIND", "KING", "KINK", "KISS", "KITE", "KITS", "KNEE", "KNEW", "KNIT", "KNOB", "KNOT", "KNOW", "LABS", "LACE", "LACK", "LACY",
    "LADS", "LADY", "LAGS", "LAID", "LAIR", "LAKE", "LAMB", "LAME", "LAMP", "LAND", "LANE", "LANK", "LAPS", "LARD", "LARK", "LASH", "LASS",
    "LAST", "LATE", "LAUD", "LAVA", "LAWN", "LAWS", "LAYS", "LAZY", "LEAD", "LEAF", "LEAK", "LEAN", "LEAP", "LEFT", "LEGS", "LEND", "LENS",
    "LENT", "LESS", "LEST", "LEVY", "LIAR", "LICE", "LICK", "LIDS", "LIED", "LIEN", "LIES", "LIEU", "LIFE", "LIFT", "LIKE", "LIMB", "LIME",
    "LIMP", "LINE", "LINK", "LINT", "LION", "LIPS", "LISP", "LIST", "LIVE", "LOAD", "LOAF", "LOAM", "LOAN", "LOBE", "LOBS", "LOCK", "LODE",
    "LOFT", "LOGO", "LOGS", "LONE", "LONG", "LOOK", "LOOM", "LOOP", "LOOT", "LORD", "LORE", "LORN", "LOSE", "LOSS", "LOST", "LOTS", "LOUD",
    "LOUT", "LOVE", "LOWS", "LUCK", "LUGE", "LUGS", "LULL", "LUMP", "LUNE", "LUNG", "LURE", "LURK", "LUSH", "LUST", "LYNX", "LYRE", "MACE",
    "MADE", "MAID", "MAIL", "MAIM", "MAIN", "MAKE", "MALE", "MALL", "MALT", "MAMA", "MANE", "MANY", "MAPS", "MARE", "MARK", "MARS", "MASH",
    "MASK", "MASS", "MAST", "MATE", "MATH", "MATS", "MAZE", "MEAD", "MEAL", "MEAN", "MEAT", "MEEK", "MEET", "MELD", "MELT", "MEMO", "MEND",
    "MENU", "MERE", "MESH", "MESS", "MICE", "MILD", "MILE", "MILK", "MILL", "MIME", "MIND", "MINE", "MINK", "MINT", "MINX", "MIRE", "MISS",
    "MIST", "MITE", "MITT", "MOAN", "MOAT", "MOBS", "MOCK", "MODE", "MOLD", "MOLE", "MOLT", "MONK", "MOOD", "MOON", "MOOR", "MOOT", "MOPS",
    "MORE", "MORN", "MOSS", "MOST", "MOTH", "MOVE", "MUCH", "MUCK", "MUDS", "MUFF", "MUGS", "MULE", "MUMM", "MUMS", "MURK", "MUSE", "MUSH",
    "MUSK", "MUST", "MUTE", "MUTT", "MYTH", "NABS", "NAGS", "NAIL", "NAME", "NAPE", "NAPS", "NAVY", "NAYS", "NEAR", "NEAT", "NECK", "NEED",
    "NEON", "NERD", "NEST", "NETS", "NEWS", "NEWT", "NEXT", "NIBS", "NICE", "NICK", "NINE", "NIPS", "NITS", "NODE", "NODS", "NOEL", "NOES",
    "NONE", "NOOK", "NOON", "NOPE", "NORM", "NOSE", "NOSY", "NOTE", "NOUN", "NOVA", "NUBS", "NUDE", "NUKE", "NULL", "NUMB", "NUNS", "NUTS",
    "OAFS", "OAKS", "OARS", "OATH", "OATS", "OBEY", "ODDS", "ODES", "ODOR", "OFFS", "OGLE", "OILS", "OILY", "OKAY", "OKRA", "OMEN", "OMIT",
    "ONCE", "ONES", "ONLY", "ONTO", "ONUS", "OOZE", "OPAL", "OPEN", "OPTS", "OPUS", "ORAL", "ORBS", "ORCA", "ORES", "OURS", "OUST", "OUTS",
    "OVAL", "OVEN", "OVER", "OWED", "OWES", "OWLS", "OWNS", "PACE", "PACK", "PACT", "PADS", "PAGE", "PAID", "PAIL", "PAIN", "PAIR", "PALE",
    "PALM", "PALS", "PANE", "PANG", "PANS", "PAPA", "PARE", "PARK", "PART", "PASS", "PAST", "PATH", "PATS", "PAVE", "PAWN", "PAWS", "PAYS",
    "PEAK", "PEAL", "PEAR", "PEAS", "PEAT", "PECK", "PEEK", "PEEL", "PEEP", "PEER", "PEGS", "PELT", "PENS", "PENT", "PEON", "PERK", "PERM",
    "PEST", "PETS", "PICK", "PIER", "PIES", "PIGS", "PIKE", "PILE", "PILL", "PINE", "PING", "PINK", "PINS", "PINT", "PIPE", "PITS", "PITY",
    "PLAN", "PLAT", "PLAY", "PLEA", "PLED", "PLOW", "PLOY", "PLUG", "PLUM", "PLUS", "POCK", "PODS", "POEM", "POET", "POKE", "POKY", "POLE",
    "POLL", "POLO", "POMP", "POND", "PONY", "POOH", "POOL", "POOP", "POOR", "POPE", "POPS", "PORE", "PORK", "PORT", "POSE", "POSH", "POST",
    "POTS", "POUR", "POUT", "PRAY", "PREP", "PREY", "PRIM", "PROD", "PROM", "PROP", "PROW", "PUBS", "PUCK", "PUDS", "PUFF", "PUGS", "PULL",
    "PULP", "PUMP", "PUNS", "PUNK", "PUNS", "PUPS", "PURE", "PURL", "PURR", "PUSH", "PUTS", "PUTT", "QUAD", "QUAY", "QUID", "QUIP", "QUIT",
    "QUIZ", "RACE", "RACK", "RAFT", "RAGE", "RAGS", "RAID", "RAIL", "RAIN", "RAKE", "RAMP", "RAMS", "RANG", "RANK", "RANT", "RAPS", "RAPT",
    "RARE", "RASH", "RASP", "RATE", "RATS", "RAVE", "RAYS", "RAZE", "READ", "REAL", "REAM", "REAP", "REAR", "REDO", "REDS", "REED", "REEF",
    "REEK", "REEL", "REFS", "REIN", "RELY", "REND", "RENT", "REST", "RIBS", "RICE", "RICH", "RIDE", "RIDS", "RIFF", "RIFT", "RIGS", "RILE",
    "RILL", "RIME", "RIMS", "RIND", "RING", "RINK", "RIOT", "RIPE", "RIPS", "RISE", "RISK", "RITE", "ROAD", "ROAM", "ROAR", "ROBE", "ROBS",
    "ROCK", "RODE", "RODS", "ROLE", "ROLL", "ROMP", "ROOF", "ROOK", "ROOM", "ROOT", "ROPE", "ROSE", "ROSY", "ROTS", "ROUT", "ROVE", "ROWS",
    "RUBE", "RUBS", "RUBY", "RUCK", "RUDE", "RUED", "RUES", "RUFF", "RUGS", "RUIN", "RULE", "RUMP", "RUMS", "RUNE", "RUNG", "RUNS", "RUNT",
    "RUSE", "RUSH", "RUST", "RUTH", "RUTS", "SACK", "SAFE", "SAGA", "SAGE", "SAGS", "SAID", "SAIL", "SAKE", "SALE", "SALT", "SAME", "SAND",
    "SANE", "SANG", "SANK", "SAPS", "SARI", "SASH", "SASS", "SAVE", "SAWS", "SAYS", "SCAB", "SCAM", "SCAN", "SCAR", "SEAL", "SEAM", "SEAR",
    "SEAS", "SEAT", "SECT", "SEED", "SEEK", "SEEM", "SEEN", "SEEP", "SEER", "SEES", "SELF", "SELL", "SEMI", "SEND", "SENT", "SEPT", "SERA",
    "SETS", "SEWN", "SHAG", "SHAM", "SHED", "SHIM", "SHIN", "SHIP", "SHIV", "SHMO", "SHOD", "SHOE", "SHOO", "SHOP", "SHOT", "SHOW", "SHUN",
    "SHUT", "SICK", "SIDE", "SIFT", "SIGH", "SIGN", "SILK", "SILO", "SILT", "SINE", "SING", "SINK", "SIPS", "SIRE", "SIRS", "SITE", "SITS",
    "SIZE", "SKID", "SKIM", "SKIN", "SKIP", "SKIT", "SLAB", "SLAG", "SLAM", "SLAP", "SLAT", "SLAY", "SLED", "SLEW", "SLID", "SLIM", "SLIT",
    "SLOB", "SLOP", "SLOT", "SLOW", "SLUG", "SLUM", "SLUR", "SMOG", "SNAP", "SNAG", "SNIP", "SNIT", "SNOB", "SNOT", "SNOW", "SNUB", "SNUG",
    "SOAK", "SOAP", "SOAR", "SOBS", "SOCK", "SODA", "SODS", "SOFA", "SOFT", "SOIL", "SOLD", "SOLE", "SOLO", "SOME", "SONG", "SONS", "SOON",
    "SOOT", "SOPS", "SORE", "SORT", "SOTS", "SOUL", "SOUP", "SOUR", "SOWN", "SOWS", "SPAM", "SPAN", "SPAR", "SPAS", "SPAT", "SPEC", "SPED",
    "SPIN", "SPIT", "SPOT", "SPRY", "SPUD", "SPUN", "SPUR", "STAB", "STAG", "STAR", "STAY", "STEM", "STEP", "STEW", "STIR", "STOP", "STOW",
    "STUB", "STUD", "STUN", "STYE", "SUBS", "SUCH", "SUDS", "SUED", "SUES", "SUIT", "SULK", "SUMO", "SUMS", "SUNG", "SUNK", "SUNS", "SURE",
    "SURF", "SWAN", "SWAP", "SWAT", "SWAY", "SWIM", "SWUM", "TABS", "TACK", "TACO", "TACT", "TAGS", "TAIL", "TAKE", "TALE", "TALK", "TALL",
    "TAME", "TAMP", "TANK", "TANS", "TAPE", "TAPS", "TART", "TASK", "TAXI", "TEAK", "TEAL", "TEAM", "TEAR", "TEAS", "TECH", "TEEM", "TEEN",
    "TELL", "TEMP", "TEND", "TENS", "TENT", "TERM", "TEST", "TEXT", "THAN", "THAT", "THAW", "THEM", "THEN", "THEY", "THIN", "THIS", "THUD",
    "THUS", "TICK", "TIDE", "TIDY", "TIED", "TIER", "TIES", "TILE", "TILL", "TILT", "TIME", "TINE", "TINS", "TINT", "TINY", "TIPS", "TIRE",
    "TOAD", "TOES", "TOFU", "TOGA", "TOGS", "TOIL", "TOLD", "TOLL", "TOMB", "TOME", "TONE", "TONS", "TOOK", "TOOL", "TOOT", "TOPS", "TORE",
    "TORN", "TORT", "TOSS", "TOTE", "TOTS", "TOUR", "TOUT", "TOWN", "TOYS", "TRAM", "TRAP", "TRAY", "TREE", "TREK", "TRIM", "TRIO", "TRIP",
    "TROD", "TROT", "TRUE", "TUBA", "TUBE", "TUBS", "TUCK", "TUFT", "TUGS", "TUNE", "TURF", "TURN", "TUTU", "TWIG", "TWIN", "TWIT", "TYPE",
    "TYPO", "UGLY", "UNDO", "UNIT", "UNTO", "UPON", "URGE", "URNS", "USED", "USER", "USES", "VAIN", "VALE", "VAMP", "VANE", "VANS", "VARY",
    "VASE", "VAST", "VATS", "VEAL", "VEER", "VEIL", "VEIN", "VENT", "VERB", "VERY", "VEST", "VETO", "VETS", "VIAL", "VICE", "VIED", "VIES",
    "VIEW", "VINE", "VISA", "VISE", "VOID", "VOLT", "VOTE", "VOWS", "WADE", "WADS", "WAFT", "WAGE", "WAGS", "WAIF", "WAIL", "WAIT", "WAKE",
    "WALK", "WALL", "WAND", "WANE", "WANT", "WARD", "WARM", "WARN", "WARP", "WARS", "WART", "WARY", "WASH", "WASP", "WAVE", "WAVY", "WAXY",
    "WAYS", "WEAK", "WEAN", "WEAR", "WEDS", "WEED", "WEEK", "WEEP", "WELD", "WELL", "WELT", "WENT", "WEPT", "WERE", "WEST", "WETS", "WHAT",
    "WHEN", "WHET", "WHEY", "WHIG", "WHIM", "WHIP", "WHIR", "WHIZ", "WHOM", "WICK", "WIDE", "WIFE", "WIGS", "WILD", "WILE", "WILL", "WILT",
    "WILY", "WIMP", "WIND", "WINE", "WING", "WINK", "WINS", "WIPE", "WIRE", "WIRY", "WISE", "WISH", "WISP", "WITH", "WITS", "WOKE", "WOKS",
    "WOLF", "WOMB", "WONT", "WOOD", "WOOF", "WOOL", "WOOS", "WORD", "WORE", "WORK", "WORM", "WORN", "WORT", "WOVE", "WRAP", "WREN", "WRIT",
    "YAKS", "YAMS", "YANG", "YANK", "YAPS", "YARD", "YARN", "YAWN", "YAWL", "YAWS", "YEAH", "YEAR", "YEAS", "YELL", "YELP", "YEWS", "YIDS",
    "YOGA", "YOGI", "YOKE", "YOLK", "YORE", "YOUR", "YOWL", "YOYO", "YULE", "YUPS", "ZANY", "ZAPS", "ZEAL", "ZEBU", "ZERO", "ZEST", "ZINC",
    "ZIPS", "ZITS", "ZONE", "ZOOM", "ZOOS",
    # 5-letter words
    "ABIDE", "ABOUT", "ABOVE", "ABUSE", "ACIDS", "ACRES", "ACTED", "ACTOR", "ACUTE", "ADAPT", "ADDED", "ADMIT", "ADOPT", "ADULT", "AFTER",
    "AGAIN", "AGENT", "AGREE", "AIDED", "AIMED", "ALARM", "ALBUM", "ALERT", "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALLEY", "ALLOT", "ALLOW",
    "ALLOY", "ALONE", "ALONG", "ALOOF", "ALPHA", "ALTER", "AMONG", "AMPLE", "AMUSE", "ANGEL", "ANGER", "ANGLE", "ANGRY", "ANKLE", "ANNEX",
    "ANTIC", "APART", "APPLE", "APPLY", "APRON", "ARENA", "ARGUE", "ARISE", "ARMOR", "AROMA", "AROSE", "ARRAY", "ARROW", "ARSON", "ASIDE",
    "ASSET", "ATLAS", "ATTIC", "AUDIO", "AUDIT", "AVOID", "AWAKE", "AWARD", "AWARE", "AWFUL", "BACON", "BADGE", "BADLY", "BAGEL", "BAKER",
    "BALLS", "BANDS", "BANKS", "BARON", "BASED", "BASES", "BASIC", "BASIN", "BASIS", "BATCH", "BEACH", "BEADS", "BEAMS", "BEANS", "BEARD",
    "BEARS", "BEAST", "BEERS", "BEGAN", "BEGIN", "BEGUN", "BEING", "BELLS", "BELLY", "BELOW", "BELTS", "BENCH", "BERRY", "BILLS", "BIRDS",
    "BIRTH", "BLACK", "BLADE", "BLAME", "BLAND", "BLANK", "BLAST", "BLAZE", "BLEED", "BLEND", "BLESS", "BLIND", "BLINK", "BLISS", "BLOCK",
    "BLOND", "BLOOD", "BLOWN", "BLOWS", "BLUES", "BLUNT", "BLURB", "BLURT", "BLUSH", "BOARD", "BOAST", "BOATS", "BOGUS", "BOILS", "BOLTS",
    "BOMBS", "BONDS", "BONES", "BONUS", "BOOKS", "BOOST", "BOOTH", "BOOTS", "BOOZE", "BORED", "BORNE", "BOSSY", "BOTCH", "BOUND", "BOXER",
    "BRAIN", "BRAKE", "BRAND", "BRASS", "BRAVE", "BREAD", "BREAK", "BREED", "BRICK", "BRIDE", "BRIEF", "BRING", "BRINK", "BRISK", "BROAD",
    "BROIL", "BROKE", "BROOK", "BROOM", "BROTH", "BROWN", "BRUSH", "BUILD", "BUILT", "BUMPS", "BUNCH", "BUNNY", "BURNS", "BURST", "BUSES",
    "BUYER", "CABIN", "CABLE", "CACHE", "CAMEL", "CAMPS", "CANAL", "CANDY", "CARDS", "CARGO", "CAROL", "CARRY", "CARVE", "CASES", "CATCH",
    "CATER", "CAUSE", "CEASE", "CHAIN", "CHAIR", "CHALK", "CHAMP", "CHANT", "CHAOS", "CHARM", "CHART", "CHASE", "CHEAP", "CHEAT", "CHECK",
    "CHEEK", "CHEER", "CHESS", "CHEST", "CHICK", "CHIEF", "CHILD", "CHILL", "CHINA", "CHIPS", "CHOIR", "CHORD", "CHORE", "CHOSE", "CHUNK",
    "CIGAR", "CINCH", "CIRCA", "CIVIL", "CLAIM", "CLAMP", "CLASH", "CLASP", "CLASS", "CLEAN", "CLEAR", "CLERK", "CLICK", "CLIFF", "CLIMB",
    "CLING", "CLOAK", "CLOCK", "CLONE", "CLOSE", "CLOTH", "CLOUD", "CLOUT", "CLOWN", "CLUBS", "CLUCK", "CLUES", "CLUMP", "COACH", "COAST",
    "COCOA", "COILS", "COINS", "COLOR", "COLON", "COMET", "COMIC", "COMMA", "CORAL", "CORES", "CORPS", "COSTS", "COUCH", "COUGH", "COULD",
    "COUNT", "COUPE", "COURT", "COVER", "CRACK", "CRAFT", "CRANE", "CRASH", "CRATE", "CRAVE", "CRAWL", "CRAZE", "CRAZY", "CREAM", "CREED",
    "CREEK", "CREEP", "CREST", "CRISP", "CROSS", "CROWD", "CROWN", "CRUDE", "CRUEL", "CRUSH", "CRUST", "CUBIC", "CURLY", "CURSE", "CURVE",
    "CYCLE", "DADDY", "DAILY", "DAIRY", "DANCE", "DATED", "DATES", "DEALT", "DEATH", "DEBIT", "DEBUT", "DECAY", "DECOR", "DECOY", "DECRY",
    "DEFER", "DEITY", "DELAY", "DELTA", "DELVE", "DEMON", "DEMOS", "DENIM", "DENSE", "DEPOT", "DEPTH", "DERBY", "DESKS", "DETER", "DETOX",
    "DIARY", "DICEY", "DIGIT", "DINER", "DINGY", "DISCO", "DITCH", "DITTO", "DIVER", "DIZZY", "DODGE", "DOING", "DOLLS", "DONOR", "DONUT",
    "DOORS", "DORMS", "DOSES", "DOUBT", "DOUGH", "DOWNS", "DOZEN", "DRAFT", "DRAIN", "DRAKE", "DRAMA", "DRANK", "DRAPE", "DRAWL", "DRAWN",
    "DRAWS", "DREAD", "DREAM", "DRESS", "DRIED", "DRIER", "DRIFT", "DRILL", "DRINK", "DRIVE", "DROIT", "DROLL", "DRONE", "DROOL", "DROOP",
    "DROPS", "DROSS", "DROVE", "DROWN", "DRUGS", "DRUMS", "DRUNK", "DRYLY", "DUCKS", "DUCTS", "DULLY", "DUMMY", "DUMPS", "DUNCE", "DUNES",
    "DUSTY", "DWARF", "DWELL", "DYING", "EAGER", "EAGLE", "EARLY", "EARTH", "EASED", "EATEN", "EATER", "EBONY", "EDGED", "EDGES", "EDICT",
    "EIGHT", "EJECT", "ELBOW", "ELDER", "ELECT", "ELITE", "ELOPE", "ELUDE", "EMAIL", "EMBER", "EMPTY", "ENDED", "ENEMY", "ENJOY", "ENNUI",
    "ENTER", "ENTRY", "ENVOY", "EQUAL", "EQUIP", "ERASE", "ERECT", "ERROR", "ERUPT", "ESSAY", "ETHIC", "EVADE", "EVENT", "EVERY", "EXACT",
    "EXALT", "EXAMS", "EXCEL", "EXERT", "EXILE", "EXIST", "EXTRA", "EXUDE", "FABLE", "FACED", "FACES", "FACTS", "FAINT", "FAIRY", "FAITH",
    "FAKED", "FALSE", "FAMED", "FANCY", "FANGS", "FARMS", "FATAL", "FATTY", "FAULT", "FAVOR", "FEARS", "FEAST", "FEATS", "FEEDS", "FEELS",
    "FEIGN", "FEINT", "FENCE", "FENDS", "FERRY", "FETAL", "FETCH", "FETID", "FEVER", "FEWER", "FIBER", "FIELD", "FIEND", "FIERY", "FIFTH",
    "FIFTY", "FIGHT", "FILCH", "FILED", "FILER", "FILET", "FILLS", "FILMS", "FILMY", "FILTH", "FINAL", "FINCH", "FINDS", "FINER", "FINES",
    "FIRED", "FIRES", "FIRMS", "FIRST", "FISHY", "FISTS", "FIXED", "FIXER", "FLAGS", "FLAIR", "FLAKE", "FLAKY", "FLAME", "FLANK", "FLAPS",
    "FLARE", "FLASH", "FLASK", "FLATS", "FLAXY", "FLEAS", "FLECK", "FLESH", "FLICK", "FLIER", "FLIES", "FLING", "FLINT", "FLIPS", "FLIRT",
    "FLOAT", "FLOCK", "FLOOD", "FLOOR", "FLOSS", "FLOUR", "FLOUT", "FLOWN", "FLOWS", "FLUFF", "FLUID", "FLUKE", "FLUNG", "FLUSH", "FLUTE",
    "FOAMY", "FOCAL", "FOCUS", "FOGGY", "FOILS", "FOLDS", "FOLKS", "FOLLY", "FONTS", "FOODS", "FOOLS", "FORAY", "FORCE", "FORGE", "FORMS",
    "FORTE", "FORTH", "FORTY", "FORUM", "FOSSIL", "FOUND", "FOUNT", "FOURS", "FOWLS", "FOXES", "FOYER", "FRAIL", "FRAME", "FRANK", "FRAUD",
    "FRAYS", "FREAK", "FREED", "FRESH", "FRIAR", "FRIED", "FRILL", "FRISK", "FRIZZ", "FROCK", "FROGS", "FROLIC", "FRONT", "FROST", "FROTH",
    "FROWN", "FROZE", "FRUIT", "FRYER", "FUDGE", "FUELS", "FULLY", "FUMES", "FUNDS", "FUNGI", "FUNKY", "FUNNY", "FURRY", "FUSED", "FUSSY",
    "FUZZY", "GAINS", "GAMES", "GANGS", "GASES", "GATES", "GAUGE", "GAUNT", "GAUZE", "GAUZY", "GAZED", "GEARS", "GEESE", "GENES", "GENIE",
    "GENRE", "GERMS", "GHOST", "GIANT", "GIFTS", "GIRLS", "GIVEN", "GIVER", "GIVES", "GLAND", "GLARE", "GLASS", "GLAZE", "GLEAM", "GLEAN",
    "GLIDE", "GLINT", "GLOBE", "GLOOM", "GLORY", "GLOSS", "GLOVE", "GLOWS", "GLUED", "GNOME", "GOATS", "GODLY", "GOING", "GOODS", "GOODY",
    "GOOEY", "GOOFY", "GOOSE", "GORGE", "GOUGE", "GOURD", "GRACE", "GRADE", "GRAFT", "GRAIN", "GRAND", "GRANT", "GRAPE", "GRAPH", "GRASP",
    "GRASS", "GRATE", "GRAVE", "GRAVY", "GRAYS", "GRAZE", "GREED", "GREEN", "GREET", "GRIEF", "GRILL", "GRIMY", "GRIND", "GRIPE", "GRITS",
    "GROAN", "GROOM", "GROPE", "GROSS", "GROUP", "GROVE", "GROWL", "GROWN", "GROWS", "GRUEL", "GRUFF", "GRUNT", "GUARD", "GUAVA", "GUESS",
    "GUEST", "GUIDE", "GUILD", "GUILT", "GUISE", "GULCH", "GULLS", "GULPS", "GUMMY", "GUSTO", "GUSTY", "HABIT", "HAIRS", "HAIRY", "HALLS",
    "HALTS", "HALVE", "HANDS", "HANDY", "HANGS", "HAPPY", "HARDY", "HARMS", "HARPS", "HARSH", "HASTE", "HASTY", "HATCH", "HATED", "HATER",
    "HATES", "HAUNT", "HAVEN", "HAVOC", "HAWKS", "HAZEL", "HEADS", "HEADY", "HEALS", "HEAPS", "HEARD", "HEARS", "HEART", "HEATS", "HEAVE",
    "HEAVY", "HEDGE", "HEEDS", "HEELS", "HEFTY", "HEIST", "HELLO", "HELPS", "HENCE", "HERBS", "HERDS", "HERON", "HILLS", "HILLY", "HINGE",
    "HINTS", "HIPPO", "HIRED", "HITCH", "HIVES", "HOBBY", "HOIST", "HOLDS", "HOLES", "HOLLY", "HOMER", "HOMES", "HONEY", "HONOR", "HOODS",
    "HOOKS", "HOPED", "HOPES", "HORDE", "HORNS", "HORSE", "HOSED", "HOSTS", "HOTEL", "HOUND", "HOURS", "HOUSE", "HOVER", "HUMAN", "HUMID",
    "HUMOR", "HUMPS", "HUNCH", "HUNKS", "HUNTS", "HURRY", "HURTS", "HYENA", "HYMNS", "ICING", "IDEAL", "IDEAS", "IDIOM", "IDIOT", "IDLED",
    "IDOLS", "IMAGE", "IMPLY", "INCUR", "INDEX", "INFER", "INNER", "INPUT", "INTRO", "IRATE", "IRKED", "IRONY", "ISSUE", "ITEMS", "IVORY",
    "JACKS", "JADED", "JAILS", "JEANS", "JEEPS", "JELLY", "JERKS", "JERKY", "JESTS", "JETTY", "JEWEL", "JIFFY", "JINKS", "JOINT", "JOKER",
    "JOKES", "JOLLY", "JOLTS", "JOUST", "JUDGE", "JUICE", "JUICY", "JUMBO", "JUMPS", "JUMPY", "JUNKY", "JUROR", "KEEPS", "KICKS", "KILLS",
    "KINDS", "KINGS", "KIOSK", "KITES", "KITTY", "KNACK", "KNEAD", "KNEED", "KNEEL", "KNEES", "KNELT", "KNIFE", "KNOBS", "KNOCK", "KNOLL",
    "KNOTS", "KNOWN", "KNOWS", "KUDOS", "LABEL", "LABOR", "LACED", "LACKS", "LAGER", "LAKES", "LAMBS", "LAMPS", "LANDS", "LANES", "LAPSE",
    "LARGE", "LARVA", "LASER", "LASSO", "LATCH", "LATER", "LATEX", "LATIN", "LAUGH", "LAWNS", "LAYER", "LEADS", "LEAFY", "LEAKY", "LEAPS",
    "LEAPT", "LEARN", "LEASE", "LEASH", "LEAST", "LEAVE", "LEDGE", "LEGAL", "LEMON", "LENDS", "LEPER", "LEVEL", "LEVER", "LIBEL", "LIEGE",
    "LIFTS", "LIGHT", "LIKED", "LIKEN", "LIKES", "LILAC", "LIMBO", "LIMBS", "LIMES", "LIMIT", "LIMPS", "LINED", "LINEN", "LINER", "LINES",
    "LINGO", "LINKS", "LIONS", "LISTS", "LITER", "LIVED", "LIVEN", "LIVER", "LIVES", "LIVID", "LLAMA", "LOADS", "LOAMY", "LOANS", "LOBBY",
    "LOCAL", "LOCKS", "LOCUS", "LODGE", "LOFTY", "LOGIC", "LOGOS", "LOINS", "LONER", "LOOKS", "LOOMS", "LOONY", "LOOPS", "LOOPY", "LOOSE",
    "LORDS", "LOSER", "LOSES", "LOTUS", "LOUSE", "LOUSY", "LOVED", "LOVER", "LOVES", "LOWER", "LOWLY", "LOYAL", "LUCID", "LUCKY", "LUMPS",
    "LUMPY", "LUNAR", "LUNCH", "LUNGE", "LUNGS", "LURCH", "LURED", "LURES", "LURKS", "LUSTY", "LYING", "LYRIC", "MACHO", "MACRO", "MADAM",
    "MADLY", "MAGIC", "MAILS", "MAIMS", "MAINS", "MAIZE", "MAJOR", "MAKER", "MALES", "MALLS", "MANIC", "MANOR", "MAPLE", "MARCH", "MARKS",
    "MARRY", "MARSH", "MASKS", "MASON", "MASSE", "MATCH", "MATED", "MATES", "MAYOR", "MAZES", "MEALS", "MEANS", "MEANT", "MEATS", "MEATY",
    "MEDAL", "MEDIA", "MELEE", "MELON", "MELTS", "MENUS", "MERCY", "MERGE", "MERIT", "MERRY", "MESSY", "METAL", "METER", "METRO", "MICRO",
    "MIDST", "MIGHT", "MILES", "MILLS", "MIMIC", "MINCE", "MINDS", "MINED", "MINER", "MINES", "MINOR", "MINUS", "MINTS", "MINTY", "MIRTH",
    "MISER", "MISTY", "MITES", "MITRE", "MITTS", "MIXED", "MIXER", "MIXES", "MOANS", "MOATS", "MOCKS", "MODEL", "MODEM", "MODES", "MOIST",
    "MOLAR", "MOLDS", "MOLDY", "MOLES", "MOLTS", "MONEY", "MONKS", "MONTH", "MOODS", "MOODY", "MOONS", "MOOSE", "MOPES", "MORAL", "MORPH",
    "MORSE", "MOSSY", "MOTEL", "MOTHS", "MOTIF", "MOTOR", "MOTTO", "MOULD", "MOUND", "MOUNT", "MOURN", "MOUSE", "MOUSY", "MOUTH", "MOVED",
    "MOVER", "MOVES", "MOVIE", "MOWER", "MUCUS", "MUDDY", "MUFFS", "MULCH", "MULES", "MUMBO", "MUMMY", "MUNCH", "MURAL", "MURKY", "MUSED",
    "MUSES", "MUSHY", "MUSIC", "MUSKY", "MUSTY", "MUTED", "MYTHS", "NAILS", "NAIVE", "NAKED", "NAMED", "NAMES", "NANNY", "NASAL", "NASTY",
    "NAVAL", "NAVEL", "NEEDY", "NERVE", "NERVY", "NESTS", "NEVER", "NEWER", "NEWLY", "NEWTS", "NICER", "NICHE", "NIFTY", "NIGHT", "NINJA",
    "NINTH", "NOBLE", "NODAL", "NODES", "NOISE", "NOISY", "NOMAD", "NOOKS", "NORMS", "NORTH", "NOSED", "NOSEY", "NOTCH", "NOTED", "NOTES",
    "NOUNS", "NOVEL", "NUDGE", "NURSE", "NUTTY", "NYLON", "OAKEN", "OASES", "OASIS", "OATHS", "OCCUR", "OCEAN", "ODDLY", "ODORS", "OFFER",
    "OFTEN", "OILED", "OINKS", "OLDER", "OLIVE", "OMEGA", "ONION", "ONSET", "OPENS", "OPERA", "OPTIC", "ORBIT", "ORDER", "ORGAN", "OTHER",
    "OTTER", "OUGHT", "OUNCE", "OUTER", "OUTDO", "OUTED", "OUTER", "OVALS", "OVARY", "OVENS", "OVERT", "OWNED", "OWNER", "OXIDE", "OZONE",
    "PACED", "PACER", "PACES", "PACKS", "PACTS", "PADDY", "PAGAN", "PAGED", "PAGER", "PAGES", "PAILS", "PAINS", "PAINT", "PAIRS", "PALMS",
    "PALSY", "PANDA", "PANEL", "PANGS", "PANIC", "PANSY", "PANTS", "PAPER", "PARKS", "PARTS", "PARTY", "PASTA", "PASTE", "PASTY", "PATCH",
    "PATIO", "PAUSE", "PAVED", "PAVES", "PEACE", "PEACH", "PEAKS", "PEARL", "PEARS", "PECAN", "PECKS", "PEDAL", "PEEKS", "PEELS", "PEERS",
    "PENAL", "PENCE", "PENNY", "PERCH", "PERIL", "PERKS", "PERKY", "PERMS", "PESTS", "PETAL", "PETTY", "PHASE", "PHONE", "PHONY", "PHOTO",
    "PIANO", "PICKS", "PICKY", "PIECE", "PIERS", "PIGGY", "PILED", "PILES", "PILLS", "PILOT", "PINCH", "PINED", "PINES", "PINGS", "PINKS",
    "PINKY", "PINTS", "PIOUS", "PIPED", "PIPER", "PIPES", "PITCH", "PITHY", "PITON", "PIVOT", "PIXEL", "PIZZA", "PLACE", "PLAID", "PLAIN",
    "PLANE", "PLANK", "PLANS", "PLANT", "PLATE", "PLAZA", "PLEAD", "PLEAS", "PLEAT", "PLEDGE", "PLIERS", "PLODS", "PLOPS", "PLOTS", "PLOWS",
    "PLOYS", "PLUCK", "PLUGS", "PLUMB", "PLUME", "PLUMP", "PLUMS", "PLUMS", "PLUNK", "PLUSH", "POEMS", "POESY", "POETS", "POINT", "POISE",
    "POKED", "POKER", "POKES", "POLAR", "POLES", "POLKA", "POLLS", "PONDS", "POOLS", "PORCH", "PORED", "PORES", "PORK", "POSED", "POSER",
    "POSES", "POSIT", "POSSE", "POSTS", "POUCH", "POUND", "POURS", "POWER", "PRANK", "PRAWN", "PRAYS", "PREEN", "PRESS", "PRICE", "PRICK",
    "PRIDE", "PRIED", "PRIES", "PRIME", "PRIMP", "PRINT", "PRIOR", "PRISM", "PRIZE", "PROBE", "PRODS", "PROMO", "PRONE", "PRONG", "PROOF",
    "PROPS", "PROSE", "PROUD", "PROVE", "PROWL", "PROXY", "PRUDE", "PRUNE", "PUBIC", "PUFFS", "PUFFY", "PULLS", "PULSE", "PUMPS", "PUNCH",
    "PUPIL", "PUPPY", "PUREE", "PURER", "PURGE", "PURSE", "PUSHY", "PUTTS", "PUTTY", "QUACK", "QUAFF", "QUAKE", "QUALM", "QUART", "QUASI",
    "QUEEN", "QUEER", "QUERY", "QUEST", "QUEUE", "QUICK", "QUIET", "QUILL", "QUILT", "QUIRK", "QUITE", "QUOTA", "QUOTE", "RABBI", "RACES",
    "RACKS", "RADAR", "RADII", "RADIO", "RADON", "RAFTS", "RAGED", "RAGES", "RAIDS", "RAILS", "RAINS", "RAINY", "RAISE", "RAKED", "RAKES",
    "RALLY", "RAMPS", "RANCH", "RANGE", "RANGY", "RANKS", "RAPID", "RARER", "RATED", "RATER", "RATES", "RATIO", "RATTY", "RAVED", "RAVEN",
    "RAVES", "RAZOR", "REACH", "REACT", "READS", "READY", "REALM", "REAMS", "REAPS", "REBEL", "REBUT", "RECAP", "RECUT", "REEDS", "REEDY",
    "REEFS", "REEKS", "REELS", "REFER", "REGAL", "REIGN", "REINS", "RELAX", "RELAY", "RELIC", "REMIT", "REMIX", "RENAL", "RENDS", "RENEW",
    "RENTS", "REPAY", "REPEL", "REPLY", "RERUN", "RESET", "RESIN", "RESTS", "RETRO", "REUSE", "REVEL", "REVUE", "RHINO", "RHYME", "RIDER",
    "RIDES", "RIDGE", "RIFLE", "RIFTS", "RIGHT", "RIGID", "RIGOR", "RILED", "RINDS", "RINGS", "RINSE", "RIOTS", "RIPEN", "RIPER", "RISEN",
    "RISER", "RISES", "RISKS", "RISKY", "RITES", "RITZY", "RIVAL", "RIVER", "RIVET", "ROACH", "ROADS", "ROAMS", "ROARS", "ROAST", "ROBED",
    "ROBES", "ROBIN", "ROBOT", "ROCKS", "ROCKY", "ROGUE", "ROLES", "ROLLS", "ROMAN", "ROOFS", "ROOMS", "ROOMY", "ROOST", "ROOTS", "ROPED",
    "ROPES", "ROSES", "ROTOR", "ROUGE", "ROUGH", "ROUND", "ROUSE", "ROUTE", "ROVER", "ROWDY", "ROWED", "ROYAL", "RUDER", "RUFFLE", "RUGBY",
    "RUINS", "RULED", "RULER", "RULES", "RUMOR", "RUNGS", "RUPEE", "RURAL", "RUSTY", "SADLY", "SAFER", "SAGES", "SAINT", "SALAD", "SALES",
    "SALLY", "SALON", "SALSA", "SALTS", "SALTY", "SALVE", "SANDS", "SANDY", "SANER", "SASSY", "SAUCE", "SAUCY", "SAUNA", "SAVED", "SAVER",
    "SAVES", "SAVOR", "SCALD", "SCALE", "SCALP", "SCALY", "SCANS", "SCARE", "SCARF", "SCARY", "SCENE", "SCENT", "SCOLD", "SCONE", "SCOOP",
    "SCOPE", "SCORE", "SCORN", "SCOUT", "SCOWL", "SCRAM", "SCRAP", "SCRUB", "SEALS", "SEAMS", "SEATS", "SEEDS", "SEEDY", "SEEKS", "SEEMS",
    "SEIZE", "SELLS", "SENDS", "SENSE", "SERUM", "SERVE", "SETUP", "SEVEN", "SEVER", "SHADE", "SHADY", "SHAFT", "SHAKE", "SHAKY", "SHALL",
    "SHAME", "SHANK", "SHAPE", "SHARD", "SHARE", "SHARK", "SHARP", "SHAVE", "SHAWL", "SHEAR", "SHEDS", "SHEEN", "SHEEP", "SHEER", "SHEET",
    "SHELF", "SHELL", "SHIFT", "SHIMS", "SHINE", "SHINS", "SHINY", "SHIPS", "SHIRK", "SHIRT", "SHOCK", "SHOES", "SHONE", "SHOOK", "SHOOT",
    "SHOPS", "SHORE", "SHORN", "SHORT", "SHOTS", "SHOUT", "SHOVE", "SHOWN", "SHOWS", "SHOWY", "SHREW", "SHRUB", "SHRUG", "SHUNS", "SHUNT",
    "SIDED", "SIDES", "SIEGE", "SIGHS", "SIGHT", "SIGMA", "SIGNS", "SILKS", "SILKY", "SILLY", "SINCE", "SINGE", "SINKS", "SINUS", "SITES",
    "SIXTH", "SIXTY", "SIZED", "SIZER", "SIZES", "SKATE", "SKIER", "SKIES", "SKIFF", "SKILL", "SKIMP", "SKIMS", "SKINS", "SKIPS", "SKIRT",
    "SKULL", "SKUNK", "SLABS", "SLACK", "SLAIN", "SLANT", "SLAPS", "SLASH", "SLATE", "SLAVE", "SLAYS", "SLEDS", "SLEEK", "SLEEP", "SLEPT",
    "SLICE", "SLICK", "SLIDE", "SLIME", "SLIMY", "SLING", "SLINK", "SLIPS", "SLITS", "SLOBS", "SLOPE", "SLOSH", "SLOTH", "SLOTS", "SLOWS",
    "SLUGS", "SLUMP", "SLUMS", "SLUNG", "SLUNK", "SLURP", "SLURS", "SLUSH", "SMALL", "SMART", "SMASH", "SMEAR", "SMELL", "SMELT", "SMILE",
    "SMIRK", "SMITE", "SMOCK", "SMOKE", "SMOKY", "SNACK", "SNAIL", "SNAKE", "SNAKY", "SNAPS", "SNARE", "SNARL", "SNEAK", "SNEER", "SNIDE",
    "SNIFF", "SNOBS", "SNOOP", "SNORE", "SNORT", "SNOUT", "SNOWY", "SNUBS", "SNUCK", "SNUFF", "SOAPY", "SOARS", "SOBER", "SOCKS", "SOFAS",
    "SOFTY", "SOGGY", "SOILS", "SOLAR", "SOLID", "SOLOS", "SOLVE", "SONAR", "SONGS", "SONIC", "SORRY", "SORTS", "SOULS", "SOUND", "SOUPS",
    "SOUPY", "SOUTH", "SPACE", "SPADE", "SPANK", "SPANS", "SPARE", "SPARK", "SPARS", "SPASM", "SPAWN", "SPEAK", "SPEAR", "SPECS", "SPEED",
    "SPELL", "SPEND", "SPENT", "SPICE", "SPICY", "SPIED", "SPIES", "SPILL", "SPINE", "SPINS", "SPINY", "SPITE", "SPLAT", "SPLIT", "SPOIL",
    "SPOKE", "SPOOF", "SPOOK", "SPOOL", "SPOON", "SPORE", "SPORT", "SPOTS", "SPOUT", "SPRAY", "SPREE", "SPRIG", "SPRY", "SPUDS", "SPUNK",
    "SPURN", "SPURT", "SQUAD", "SQUAT", "SQUID", "STACK", "STAFF", "STAGE", "STAIN", "STAIR", "STAKE", "STALE", "STALL", "STAMP", "STAND",
    "STANK", "STAPH", "STARE", "STARK", "STARS", "START", "STASH", "STATE", "STAVE", "STAYS", "STEAK", "STEAL", "STEAM", "STEEL", "STEEP",
    "STEER", "STEMS", "STEPS", "STERN", "STEWS", "STICK", "STIFF", "STILL", "STILTS", "STING", "STINK", "STINT", "STOCK", "STOIC", "STOKE",
    "STOLE", "STOMP", "STONE", "STONY", "STOOD", "STOOL", "STOOP", "STOPS", "STORE", "STORK", "STORM", "STORY", "STOUT", "STOVE", "STRAP",
    "STRAW", "STRAY", "STRIP", "STRUT", "STUCK", "STUDS", "STUDY", "STUFF", "STUMP", "STUNG", "STUNK", "STUNS", "STUNT", "STYLE", "SUAVE",
    "SUCKS", "SUGAR", "SUITE", "SUITS", "SULKS", "SULKY", "SUNNY", "SUPER", "SURGE", "SWAMP", "SWANS", "SWAPS", "SWARM", "SWAYS", "SWEAR",
    "SWEAT", "SWEEP", "SWEET", "SWELL", "SWEPT", "SWIFT", "SWIMS", "SWINE", "SWING", "SWIPE", "SWIRL", "SWISS", "SWORD", "SWORE", "SWORN",
    "SWUNG", "SYRUP", "TABLE", "TACIT", "TACKS", "TACKY", "TACOS", "TAINT", "TAKEN", "TAKER", "TAKES", "TALES", "TALKS", "TALLY", "TALON",
    "TAMED", "TAMER", "TANGO", "TANGY", "TANKS", "TAPED", "TAPER", "TAPES", "TARDY", "TARPS", "TASTE", "TASTY", "TAUNT", "TAXES", "TEACH",
    "TEAMS", "TEARS", "TEARY", "TEASE", "TECHS", "TEDDY", "TEENS", "TEETH", "TEMPO", "TENDS", "TENOR", "TENSE", "TENTH", "TENTS", "TEPID",
    "TERMS", "TESTS", "TEXTS", "THANK", "THEFT", "THEME", "THERE", "THESE", "THICK", "THIEF", "THIGH", "THING", "THINK", "THIRD", "THONG",
    "THORN", "THOSE", "THREE", "THREW", "THROB", "THROW", "THUDS", "THUGS", "THUMB", "THUMP", "TIDAL", "TIDES", "TIGER", "TIGHT", "TILED",
    "TILES", "TILTS", "TIMED", "TIMER", "TIMES", "TIMID", "TINTS", "TIPSY", "TIRED", "TIRES", "TITLE", "TOAST", "TODAY", "TOESBUILD", "TOILE", "TOKEN",
    "TOLLS", "TOMBS", "TONAL", "TONED", "TONER", "TONES", "TONGS", "TONIC", "TOOLS", "TOOTH", "TOPIC", "TOPAZ", "TORCH", "TORSO", "TOTAL",
    "TOTEM", "TOUCH", "TOUGH", "TOURS", "TOWEL", "TOWER", "TOWNS", "TOXIC", "TRACE", "TRACK", "TRACT", "TRADE", "TRAIL", "TRAIN", "TRAIT",
    "TRAMP", "TRAPS", "TRASH", "TRAWL", "TRAYS", "TREAD", "TREAT", "TREES", "TREND", "TRIAL", "TRIBE", "TRICK", "TRIED", "TRIES", "TRILL",
    "TRIMS", "TRIPS", "TRITE", "TROLL", "TROOP", "TROTS", "TROUT", "TRUCE", "TRUCK", "TRULY", "TRUMP", "TRUNK", "TRUSS", "TRUST", "TRUTH",
    "TUBES", "TULIP", "TUMID", "TUMOR", "TUNED", "TUNER", "TUNES", "TUNIC", "TURFS", "TURNS", "TUTOR", "TWANG", "TWEAK", "TWEED", "TWEET",
    "TWICE", "TWIGS", "TWINE", "TWINS", "TWIRL", "TWIST", "TYPED", "TYPES", "TYPOS", "UDDER", "ULCER", "ULTRA", "UMBRA", "UNCLE", "UNDER",
    "UNDID", "UNDUE", "UNFIT", "UNION", "UNITE", "UNITS", "UNITY", "UNLIT", "UNTIL", "UNZIP", "UPPER", "UPSET", "URBAN", "URGED", "URGES",
    "URINE", "USAGE", "USERS", "USHER", "USING", "USUAL", "UTTER", "VAGUE", "VALET", "VALID", "VALOR", "VALUE", "VALVE", "VAPOR", "VAULT",
    "VAUNT", "VEERS", "VENOM", "VENUE", "VERGE", "VERSE", "VEXED", "VIDEO", "VIEWS", "VIGOR", "VINES", "VINYL", "VIOLA", "VIPER", "VIRAL",
    "VIRUS", "VISIT", "VISOR", "VISTA", "VITAL", "VIVID", "VOCAL", "VODKA", "VOGUE", "VOICE", "VOILA", "VOLTS", "VOMIT", "VOTED", "VOTER",
    "VOTES", "VOUCH", "VOWED", "VOWEL", "WADED", "WADER", "WADES", "WAFER", "WAGED", "WAGER", "WAGES", "WAGON", "WAIST", "WAITS", "WAIVE",
    "WAKED", "WAKEN", "WAKES", "WALKS", "WALLS", "WALTZ", "WANDS", "WANTS", "WARDS", "WARES", "WARNS", "WARPS", "WARTS", "WARTY", "WASPS",
    "WASTE", "WATCH", "WATER", "WATTS", "WAVED", "WAVER", "WAVES", "WAITS", "WAIST", "WEAKEN", "WEAKER", "WEALS", "WEALTH", "WEANS", "WEARS", "WEARY", "WEAVE", "WEDGE", "WEEDS", "WEEDY",
    "WEEKS", "WEEPS", "WEIGH", "WEIRD", "WELLS", "WELSH", "WENCH", "WHALE", "WHARF", "WHEAT", "WHEEL", "WHELP", "WHERE", "WHICH", "WHIFF",
    "WHILE", "WHIMS", "WHINE", "WHINY", "WHIPS", "WHIRL", "WHISK", "WHITE", "WHOLE", "WHOOP", "WHOSE", "WICKS", "WIDEN", "WIDER", "WIDOW",
    "WIDTH", "WIELD", "WIFES", "WIGHT", "WILDS", "WILES", "WILLS", "WINCE", "WINCH", "WINDS", "WINDY", "WINED", "WINES", "WINGS", "WINKS",
    "WIPED", "WIPER", "WIPES", "WIRED", "WIRES", "WISER", "WITCH", "WITTY", "WOKEN", "WOLFS", "WOMAN", "WOMEN", "WOODS", "WOOZY", "WORDS",
    "WORDY", "WORKS", "WORLD", "WORMS", "WORMY", "WORRY", "WORSE", "WORST", "WORTH", "WOULD", "WOUND", "WOVEN", "WRACK", "WRAPS", "WRATH",
    "WREAK", "WRECK", "WREST", "WRING", "WRIST", "WRITE", "WRONG", "WROTE", "YACHT", "YANKS", "YARDS", "YARNS", "YAWNS", "YEARN", "YEARS",
    "YEAST", "YELLS", "YELPS", "YIELD", "YOKES", "YOLKS", "YOUNG", "YOURS", "YOUTH", "ZEBRA", "ZEROS", "ZESTY", "ZONES", "ZOOMS"
}


def load_dictionary_words(db: Session) -> dict[int, set[str]]:
    """
    Load only verified common words for puzzle generation.

    Uses CLUE_TEMPLATES (primary) plus EXTRA_COMMON_WORDS for variety.
    All words are verified as real, recognizable English words.
    """
    words_by_length: dict[int, set[str]] = {}

    # Add all words from CLUE_TEMPLATES
    for word in CLUE_TEMPLATES.keys():
        length = len(word)
        if length not in words_by_length:
            words_by_length[length] = set()
        words_by_length[length].add(word.upper())

    # Add extra common words
    for word in EXTRA_COMMON_WORDS:
        length = len(word)
        if 3 <= length <= 5:  # Only 3-5 letter words for mini crosswords
            if length not in words_by_length:
                words_by_length[length] = set()
            words_by_length[length].add(word.upper())

    total = sum(len(w) for w in words_by_length.values())
    logger.info(f"Loaded {total} verified common words")
    return words_by_length


def extract_word_slots(pattern: list[list[str]]) -> list[dict]:
    """Extract word slots from a pattern grid."""
    size = len(pattern)
    slots = []
    clue_num = 1

    for r in range(size):
        for c in range(size):
            if pattern[r][c] == BLACK:
                continue

            # Check if this cell starts an across word
            starts_across = (c == 0 or pattern[r][c-1] == BLACK) and \
                           (c + 1 < size and pattern[r][c+1] != BLACK)

            # Check if this cell starts a down word
            starts_down = (r == 0 or pattern[r-1][c] == BLACK) and \
                         (r + 1 < size and pattern[r+1][c] != BLACK)

            if starts_across or starts_down:
                if starts_across:
                    # Calculate length
                    length = 0
                    cc = c
                    while cc < size and pattern[r][cc] != BLACK:
                        length += 1
                        cc += 1
                    if length >= 3:  # Only include 3+ letter words
                        slots.append({
                            "number": clue_num,
                            "direction": "across",
                            "row": r,
                            "col": c,
                            "length": length,
                            "cells": [(r, c + i) for i in range(length)],
                        })

                if starts_down:
                    # Calculate length
                    length = 0
                    rr = r
                    while rr < size and pattern[rr][c] != BLACK:
                        length += 1
                        rr += 1
                    if length >= 3:  # Only include 3+ letter words
                        slots.append({
                            "number": clue_num,
                            "direction": "down",
                            "row": r,
                            "col": c,
                            "length": length,
                            "cells": [(r + i, c) for i in range(length)],
                        })

                if starts_across or starts_down:
                    clue_num += 1

    return slots


def get_pattern_for_slot(solution: list[list[str]], slot: dict) -> list[Optional[str]]:
    """Get current letter constraints for a slot."""
    pattern = []
    for r, c in slot["cells"]:
        cell = solution[r][c]
        if cell == "." or cell == BLACK:
            pattern.append(None)
        else:
            pattern.append(cell)
    return pattern


def matches_pattern(word: str, pattern: list[Optional[str]]) -> bool:
    """Check if word matches the pattern constraints."""
    if len(word) != len(pattern):
        return False
    for i, char in enumerate(pattern):
        if char is not None and word[i] != char:
            return False
    return True


def fill_puzzle_with_backtracking(
    pattern: list[list[str]],
    slots: list[dict],
    words_by_length: dict[int, set[str]],
    max_attempts: int = 50000
) -> Optional[list[list[str]]]:
    """Fill a puzzle pattern with valid words using backtracking."""
    size = len(pattern)
    solution = [row[:] for row in pattern]  # Copy pattern

    used_words: set[str] = set()
    backtrack_count = [0]  # Use list to allow modification in nested function
    filled_slots: list[int] = []  # Track which slots have been filled

    def count_constraints(slot: dict) -> int:
        """Count how many cells already have letters."""
        count = 0
        for r, c in slot["cells"]:
            if solution[r][c] not in (".", BLACK):
                count += 1
        return count

    def get_candidates_for_slot(slot: dict) -> list[str]:
        """Get candidate words that match current constraints."""
        length = slot["length"]
        if length not in words_by_length:
            return []

        current_pattern = get_pattern_for_slot(solution, slot)
        candidates = [w for w in words_by_length[length]
                     if matches_pattern(w, current_pattern) and w not in used_words]
        return candidates

    def get_next_slot(remaining_slots: list[int]) -> Optional[int]:
        """Choose the most constrained slot (fewest valid candidates)."""
        if not remaining_slots:
            return None

        best_slot = None
        best_count = float('inf')

        for idx in remaining_slots:
            slot = slots[idx]
            candidates = get_candidates_for_slot(slot)
            count = len(candidates)

            if count == 0:
                return None  # Dead end - no valid words for this slot

            if count < best_count:
                best_count = count
                best_slot = idx

        return best_slot

    def try_fill(remaining_slots: list[int]) -> bool:
        if not remaining_slots:
            return True  # All slots filled!

        if backtrack_count[0] >= max_attempts:
            return False

        # Choose most constrained slot
        slot_idx = get_next_slot(remaining_slots)
        if slot_idx is None:
            return False  # Dead end

        slot = slots[slot_idx]
        candidates = get_candidates_for_slot(slot)

        # Shuffle for variety
        random.shuffle(candidates)

        for word in candidates[:500]:  # Try many candidates
            # Place the word
            old_values = []
            for i, (r, c) in enumerate(slot["cells"]):
                old_values.append(solution[r][c])
                solution[r][c] = word[i]
            used_words.add(word)

            # Try to fill remaining slots
            new_remaining = [i for i in remaining_slots if i != slot_idx]
            if try_fill(new_remaining):
                return True

            # Backtrack
            backtrack_count[0] += 1
            used_words.discard(word)
            for i, (r, c) in enumerate(slot["cells"]):
                solution[r][c] = old_values[i]

        return False

    # Start with all slots
    all_slot_indices = list(range(len(slots)))
    if try_fill(all_slot_indices):
        return solution
    return None


def generate_validated_puzzle(
    db: Session,
    pattern_idx: int = None,
    seed: int = None
) -> Optional[dict]:
    """
    Generate a single validated crossword puzzle.

    All words are verified against the dictionary database.
    """
    if seed is not None:
        random.seed(seed)

    # Load dictionary
    words_by_length = load_dictionary_words(db)

    if not words_by_length:
        logger.error("No dictionary words found!")
        return None

    # Select pattern
    if pattern_idx is not None:
        pattern = PATTERNS[pattern_idx % len(PATTERNS)]
    else:
        pattern = random.choice(PATTERNS)

    # Extract word slots
    slots = extract_word_slots(pattern)

    if not slots:
        logger.error("No word slots found in pattern!")
        return None

    logger.info(f"Pattern has {len(slots)} word slots")

    # Try to fill the puzzle
    solution = fill_puzzle_with_backtracking(pattern, slots, words_by_length)

    if solution is None:
        logger.warning("Failed to fill puzzle with valid words")
        return None

    # Verify all words are in dictionary
    for slot in slots:
        word = "".join(solution[r][c] for r, c in slot["cells"])
        if word not in words_by_length.get(len(word), set()):
            logger.error(f"Word '{word}' not in dictionary!")
            return None

    # Build clues
    clues_across = []
    clues_down = []

    for slot in slots:
        word = "".join(solution[r][c] for r, c in slot["cells"])
        clue = get_clue_for_word(word)

        clue_entry = {
            "number": slot["number"],
            "clue": clue,
            "length": slot["length"],
            "row": slot["row"],
            "col": slot["col"],
        }

        if slot["direction"] == "across":
            clues_across.append(clue_entry)
        else:
            clues_down.append(clue_entry)

    # Create empty grid for play (hide letters, show black squares)
    size = len(pattern)
    grid = [[" " if cell != BLACK else BLACK for cell in row] for row in solution]

    logger.info(f"Successfully generated puzzle with {len(slots)} words")

    return {
        "size": size,
        "solution": solution,
        "grid": grid,
        "clues_across": sorted(clues_across, key=lambda x: x["number"]),
        "clues_down": sorted(clues_down, key=lambda x: x["number"]),
    }


def generate_weekly_puzzles(db: Session, count: int = 7, week_seed: int = None) -> list[dict]:
    """
    Generate multiple validated puzzles for a week.

    Uses different patterns and seeds for variety.
    """
    puzzles = []

    for i in range(count):
        # Use different seed for each puzzle
        seed = (week_seed or 0) + i * 12345 if week_seed else None
        pattern_idx = i % len(PATTERNS)

        puzzle = generate_validated_puzzle(db, pattern_idx=pattern_idx, seed=seed)

        if puzzle:
            puzzles.append(puzzle)
            logger.info(f"Generated puzzle {i+1}/{count}")
        else:
            # Retry with different pattern
            for retry in range(3):
                alt_pattern = (pattern_idx + retry + 1) % len(PATTERNS)
                puzzle = generate_validated_puzzle(db, pattern_idx=alt_pattern, seed=seed)
                if puzzle:
                    puzzles.append(puzzle)
                    logger.info(f"Generated puzzle {i+1}/{count} (retry {retry+1})")
                    break
            else:
                logger.error(f"Failed to generate puzzle {i+1}/{count}")

    return puzzles


# Legacy function for compatibility
def get_random_templates(count: int, seed: int = None) -> list[dict]:
    """
    Legacy function - returns empty templates that will be filled dynamically.

    The actual puzzle generation now happens in puzzle_cache.py using
    generate_weekly_puzzles() which validates against the dictionary.
    """
    if seed is not None:
        random.seed(seed)

    templates = []
    for i in range(count):
        pattern = PATTERNS[i % len(PATTERNS)]
        size = len(pattern)

        # Return pattern structure - actual filling happens later
        templates.append({
            "size": size,
            "pattern": pattern,
            "solution": pattern,  # Will be filled by cache
            "clues_across": [],
            "clues_down": [],
        })

    return templates


def validate_all_templates(db=None) -> bool:
    """Validate that puzzle generation is working."""
    logger.info(f"Loaded {len(PATTERNS)} puzzle patterns")
    logger.info(f"Loaded {len(CLUE_TEMPLATES)} clue templates")
    return True
